/*
    F3002Z1 - Bill of Materials
    VER0001 -  Tom Sampson
*/

SELECT

 '' SZEDUS -- EDI - User ID [Generic Edit] String (10)
,'' SZEDBT -- EDI - Batch Number [Generic Edit] String (15)
,'' SZEDTN -- EDI - Transaction Number [Generic Edit] String (22)
,'' SZEDLN -- EDI - Line Number [Generic Edit] Numeric (7)
,'' SZEDCT -- EDI - Document Type [Generic Edit] String (2)
,'' SZTYTN -- Type - Transaction [UDC (00 TT)] String (8)
,'' SZEDFT -- EDI - Translation Format [Generic Edit] String (10)
,'' SZEDDT -- EDI - Transmission Date [Generic Edit] Date (6)
,'' SZDRIN -- Direction Indicator [UDC (00 DN)] Character (1)
,'' SZEDDL -- EDI - Detail Lines Processed [Generic Edit] Numeric (5)
,'' SZEDSP -- EDI - Successfully Processed [Generic Edit] Character (1)
,'' SZPNID -- Trading Partner ID [Generic Edit] String (15)
,'' SZTNAC -- Transaction Action [UDC (00 TA)] String (2)
,'' SZTBM -- Type Bill of Material [UDC (40 TB)] String (3)
,'' SZKIT -- Parent (short) Item Number [Generic Edit] Numeric (8)
,'' SZKITL -- Kit - 2nd Item Number [Generic Edit] String (25)
,'' SZKITA -- 3rd Item Number - Kit [Generic Edit] String (25)
,'' SZMMCU -- Branch [Generic Edit] String (12)
,'' SZITM -- Item Number - Short [Generic Edit] Numeric (8)
,'' SZLITM -- 2nd Item Number [Generic Edit] String (25)
,'' SZAITM -- 3rd Item Number [Generic Edit] String (25)
,'' SZCMCU -- Component Branch [Generic Edit] String (12)
,'' SZCPNT -- Component Line Number [Generic Edit] Numeric (4)
,'' SZSBNT -- Substitute Item Sequence Number [Generic Edit] Numeric (5)
,'' SZPRTA -- Partials Allowed (Y/N) [Generic Edit] Character (1)
,'' SZQNTY -- Quantity - Standard Required Quantity [Generic Edit] Numeric (15)
,'' SZUM -- Unit of Measure [UDC (00 UM)] String (2)
,'' SZBQTY -- Units - Batch Quantity [Generic Edit] Numeric (15)
,'' SZUOM -- Unit of Measure as Input [UDC (00 UM)] String (2)
,'' SZFVBT -- Fixed or Variable Batch Size [Generic Edit] Character (1)
,'' SZEFFF -- Effective - From Date [Generic Edit] Date (6)
,'' SZEFFT -- Effective - Thru Date [Generic Edit] Date (6)
,'' SZFSER -- Effective From Serial Number [Generic Edit] String (25)
,'' SZTSER -- Effective Thru Serial Number [Generic Edit] String (25)
,'' SZITC -- Issue Type Code [UDC (41 IT)] Character (1)
,'' SZFTRC -- Required [Generic Edit] Character (1)
,'' SZOPTK -- Optional Item (Kit) [UDC (H40 OP)] Character (1)
,'' SZFORV -- Default Component [Generic Edit] Character (1)
,'' SZCSTM -- Component Costing Method [UDC (H40 CV)] Character (1)
,'' SZCSMP -- Costing Method - Purchasing [Generic Edit] Character (1)
,'' SZORDW -- Order With [Generic Edit] Character (1)
,'' SZFORQ -- Fixed or Variable Quantity [UDC (H40 FO)] Character (1)
,'' SZCOBY -- Co-Products/By-Products/Intermediate [UDC (H40 CO)] Character (1)
,'' SZCOTY -- Component Type [UDC (H40 CP)] Character (1)
,'' SZFRMP -- From Potency [Generic Edit] Numeric (7)
,'' SZTHRP -- Thru Potency [Generic Edit] Numeric (7)
,'' SZFRGD -- From Grade [UDC (40 LG)] String (3)
,'' SZTHGD -- Thru Grade [UDC (40 LG)] String (3)
,'' SZOPSQ -- Sequence Number - Operations [Generic Edit] Numeric (5)
,'' SZBSEQ -- Sequence - Bubble Sequence [Generic Edit] Numeric (5)
,'' SZFTRP -- Feature Planned Percent [Generic Edit] Numeric (5)
,'' SZF$RP -- Feature Cost Percent [Generic Edit] Numeric (5)
,'' SZRSCP -- Resource Percent [Generic Edit] Numeric (5)
,'' SZSCRP -- Percent - Percent of Scrap [Generic Edit] Numeric (5)
,'' SZREWP -- Percent - Rework [Generic Edit] Numeric (5)
,'' SZASIP -- Percent - As is [Generic Edit] Numeric (5)
,'' SZCPYP -- Percent - Cumulative Planned Yield [Generic Edit] Numeric (5)
,'' SZSTPP -- Operation Scrap Percent [Generic Edit] Numeric (5)
,'' SZLOVD -- Leadtime Offset Days [Generic Edit] Numeric (6)
,'' SZECO -- ECO Number [Generic Edit] String (12)
,'' SZECTY -- Engineering Change Reason [UDC (40 CR)] String (2)
,'' SZECOD -- Date - Engineering Change Date [Generic Edit] Date (6)
,'' SZDSC1 -- Description [Generic Edit] String (30)
,'' SZLNTY -- Line Type [Generic Edit] String (2)
,'' SZPRIC -- Unit Price per Primary [Generic Edit] Numeric (15)
,'' SZUNCS -- Amount - Unit Cost [Generic Edit] Numeric (15)
,'' SZPCTK -- Percent Assembly Sales Price [Generic Edit] Numeric (7)
,'' SZSHNO -- Message Number [Generic Edit] String (10)
,'' SZOMCU -- Project Business Unit [Generic Edit] String (12)
,'' SZOBJ -- Object Account [Generic Edit] String (6)
,'' SZSUB -- Subsidiary [Generic Edit] String (8)
,'' SZBREV -- Bill Revision Level [Generic Edit] String (3)
,'' SZCMRV -- Component Revision Level [Generic Edit] String (3)
,'' SZRVNO -- Last Revision No. [Generic Edit] String (2)
,'' SZUUPG -- Item Number - Use Up/Go To [Generic Edit] Numeric (8)
,'' SZURCD -- User Reserved Code [Generic Edit] String (2)
,'' SZURDT -- User Reserved Date [Generic Edit] Date (6)
,'' SZURAT -- User Reserved Amount [Generic Edit] Numeric (15)
,'' SZURRF -- User Reserved Reference [Generic Edit] String (15)
,'' SZURAB -- User Reserved Number [Generic Edit] Numeric (8)
,'' SZUSER -- User ID [Generic Edit] String (10)
,'' SZPID -- Program ID [Generic Edit] String (10)
,'' SZUPMJ -- Date - Updated [Generic Edit] Date (6)
,'' SZTDAY -- Time of Day [Generic Edit] Numeric (6)
,'' SZJOBN -- Work Station ID [Generic Edit] String (10)
,'' SZAING -- Active Ingredient Flag [Generic Edit] Character (1)
,'' SZSUCO -- Substitute Counter [Generic Edit] Integer (11)
,'' SZSTRC -- Consumption Start [Generic Edit] Numeric (15)
,'' SZENDC -- Consumption End [Generic Edit] Numeric (15)
,'' SZAPSC -- Constraints Flag [UDC (42 AC)] Character (1)
,'' SZCPNB -- Component Line Number BOM [Generic Edit] Numeric (8)
,'' SZBSEQAN -- Bubble Sequence Alpha Numeric [Generic Edit] String (5)
,'' SZBCHAR -- Lean Superflush Flag [Generic Edit] Character (1)
,'' SZBOSTR -- Prep Code [UDC (F30L PC)] String (4)

FROM

TBD