/*
    F42019 - Sales Order Header History
    VER0001 -  Tom Sampson
*/

SELECT

 '' SHKCOO -- Order Company (Order Number) [Generic Edit] String (5)
,'' SHDOCO -- Document (Order No Invoice etc.) [Generic Edit] Numeric (8)
,'' SHDCTO -- Order Type [UDC (00 DT)] String (2)
,'' SHSFXO -- Order Suffix [Generic Edit] String (3)
,'' SHMCU -- Business Unit [Generic Edit] String (12)
,'' SHCO -- Company [Generic Edit] String (5)
,'' SHOKCO -- Document Company (Original Order) [Generic Edit] String (5)
,'' SHOORN -- Original Order Number [Generic Edit] String (8)
,'' SHOCTO -- Original Order Type [UDC (00 DT)] String (2)
,'' SHRKCO -- Company - Key (Related Order) [Generic Edit] String (5)
,'' SHRORN -- Related PO/SO/WO Number [Generic Edit] String (8)
,'' SHRCTO -- Related PO/SO/WO Order Type [UDC (00 DT)] String (2)
,'' SHAN8 -- Address Number [Generic Edit] Numeric (8)
,'' SHSHAN -- Address Number - Ship To [Generic Edit] Numeric (8)
,'' SHPA8 -- Address Number - Parent [Generic Edit] Numeric (8)
,'' SHDRQJ -- Date - Requested [Generic Edit] Date (6)
,'' SHTRDJ -- Date - Order/Transaction [Generic Edit] Date (6)
,'' SHPDDJ -- Date - Scheduled Pick [Generic Edit] Date (6)
,'' SHOPDJ -- Date - Original Promised Delivery [Generic Edit] Date (6)
,'' SHADDJ -- Date - Actual Ship Date [Generic Edit] Date (6)
,'' SHCNDJ -- Date - Cancel [Generic Edit] Date (6)
,'' SHPEFJ -- Date - Price Effective Date [Generic Edit] Date (6)
,'' SHPPDJ -- Date - Promised Shipment [Generic Edit] Date (6)
,'' SHVR01 -- Reference [Generic Edit] String (25)
,'' SHVR02 -- Reference 2 [Generic Edit] String (25)
,'' SHDEL1 -- Delivery Instructions Line 1 [Generic Edit] String (30)
,'' SHDEL2 -- Delivery Instructions Line 2 [Generic Edit] String (30)
,'' SHINMG -- Print Message [UDC (40 PM)] String (10)
,'' SHPTC -- Payment Terms Code [Generic Edit] String (3)
,'' SHRYIN -- Payment Instrument [UDC (00 PY)] Character (1)
,'' SHASN -- Price and Adjustment Schedule [UDC (40 AS)] String (8)
,'' SHPRGP -- Pricing Group [UDC (40 PC)] String (8)
,'' SHTRDC -- Discount - Trade [Generic Edit] Numeric (7)
,'' SHPCRT -- Percent - Retainage [Generic Edit] Numeric (7)
,'' SHTXA1 -- Tax Rate/Area [Generic Edit] String (10)
,'' SHEXR1 -- Tax Expl Code 1 [UDC (00 EX)] String (2)
,'' SHTXCT -- Certificate Tax Exemption [Generic Edit] String (20)
,'' SHATXT -- Associated Text [Generic Edit] Character (1)
,'' SHPRIO -- Priority - Processing [UDC (H40 PR)] Character (1)
,'' SHBACK -- Backorders Allowed (Y/N) [Generic Edit] Character (1)
,'' SHSBAL -- Substitutes Allowed (Y/N) [Generic Edit] Character (1)
,'' SHHOLD -- Hold Orders Code [UDC (42 HC)] String (2)
,'' SHPLST -- Price Pick List (Y/N) [Generic Edit] Character (1)
,'' SHINVC -- Invoice Copies [Generic Edit] Numeric (2)
,'' SHNTR -- Nature of Transaction [UDC (00 NT)] String (2)
,'' SHANBY -- Buyer Number [Generic Edit] Numeric (8)
,'' SHCARS -- Carrier Number [Generic Edit] Numeric (8)
,'' SHMOT -- Mode of Transport [UDC (00 TM)] String (3)
,'' SHCOT -- Conditions of Transport [UDC (00 TC)] String (3)
,'' SHROUT -- Route Code [UDC (42 RT)] String (3)
,'' SHSTOP -- Stop Code [UDC (42 SP)] String (3)
,'' SHZON -- Zone Number [UDC (40 ZN)] String (3)
,'' SHCNID -- Container I.D. [Generic Edit] String (20)
,'' SHFRTH -- Freight Handling Code [UDC (42 FR)] String (3)
,'' SHAFT -- Apply Freight - Y/N [Generic Edit] Character (1)
,'' SHFUF1 -- AIA Document Flag [UDC (H40 FU)] Character (1)
,'' SHFRTC -- Freight Calculated (Y/N) [Generic Edit] Character (1)
,'' SHMORD -- Merge Orders (Y/N) [Generic Edit] Character (1)
,'' SHRCD -- Reason Code [UDC (42 RC)] String (3)
,'' SHFUF2 -- Post Quantities [Generic Edit] Character (1)
,'' SHOTOT -- Amount - Order Gross [Generic Edit] Numeric (15)
,'' SHTOTC -- Amount - Total Cost [Generic Edit] Numeric (15)
,'' SHWUMD -- Unit of Measure - Weight Display [UDC (00 UM)] String (2)
,'' SHVUMD -- Unit of Measure - Volume Display [UDC (00 UM)] String (2)
,'' SHAUTN -- Authorization Number - Credit Approval [Generic Edit] String (10)
,'' SHCACT -- Account Number - Credit/Bank [Generic Edit] String (25)
,'' SHCEXP -- Date - Expired (Julian) [Generic Edit] Date (6)
,'' SHSBLI -- Subledger Inactive Code [UDC (00 SI)] Character (1)
,'' SHCRMD -- Send Method [UDC (00 SM)] Character (1)
,'' SHCRRM -- Currency Mode-Foreign or Domestic Entry [UDC (H00 CY)] Character (1)
,'' SHCRCD -- Currency Code - From [Generic Edit] String (3)
,'' SHCRR -- Currency Conversion Rate - Spot Rate [Generic Edit] Numeric (15)
,'' SHLNGP -- Language [UDC (01 LP)] String (2)
,'' SHFAP -- Amount - Foreign Open [Generic Edit] Numeric (15)
,'' SHFCST -- Amount - Foreign Total Cost [Generic Edit] Numeric (15)
,'' SHORBY -- Ordered By [Generic Edit] String (10)
,'' SHTKBY -- Order Taken By [Generic Edit] String (10)
,'' SHURCD -- User Reserved Code [Generic Edit] String (2)
,'' SHURDT -- User Reserved Date [Generic Edit] Date (6)
,'' SHURAT -- User Reserved Amount [Generic Edit] Numeric (15)
,'' SHURAB -- User Reserved Number [Generic Edit] Numeric (8)
,'' SHURRF -- User Reserved Reference [Generic Edit] String (15)
,'' SHUSER -- User ID [Generic Edit] String (10)
,'' SHPID -- Program ID [Generic Edit] String (10)
,'' SHJOBN -- Work Station ID [Generic Edit] String (10)
,'' SHUPMJ -- Date - Updated [Generic Edit] Date (6)
,'' SHTDAY -- Time of Day [Generic Edit] Numeric (6)
,'' SHIR01 -- Integration Reference 01 [Generic Edit] String (30)
,'' SHIR02 -- Integration Reference 02 [Generic Edit] String (30)
,'' SHIR03 -- Integration Reference 03 [Generic Edit] String (30)
,'' SHIR04 -- Integration Reference 04 [Generic Edit] String (30)
,'' SHIR05 -- Integration Reference 05 [Generic Edit] String (30)
,'' SHVR03 -- Reference [Generic Edit] String (25)
,'' SHSOOR -- Source of Order [Generic Edit] Integer (11)
,'' SHPMDT -- Scheduled Shipment Time [Generic Edit] Numeric (6)
,'' SHRSDT -- Promised Delivery Time [Generic Edit] Numeric (6)
,'' SHRQSJ -- Date - Requested Ship [Generic Edit] Date (6)
,'' SHPSTM -- Time - Future Time 2 [Generic Edit] Numeric (6)
,'' SHPDTT -- Time - Scheduled Pick [Generic Edit] Numeric (6)
,'' SHOPTT -- Time - Original Promised Delivery [Generic Edit] Numeric (6)
,'' SHDRQT -- Requested Delivery Time [Generic Edit] Numeric (6)
,'' SHADTM -- Actual Shipment Time [Generic Edit] Numeric (6)
,'' SHADLJ -- Date - Actual Delivery [Generic Edit] Date (6)
,'' SHPBAN -- Address Number - Paid By [Generic Edit] Numeric (8)
,'' SHITAN -- Address Number - Invoiced To [Generic Edit] Numeric (8)
,'' SHFTAN -- Address Number - Forwarded To [Generic Edit] Numeric (8)
,'' SHDVAN -- Address Number - Deliver To [Generic Edit] Numeric (8)
,'' SHDOC1 -- Document (Order # Invoice etc.) [Generic Edit] Numeric (8)
,'' SHDCT4 -- Document Type [UDC (00 DT)] String (2)
,'' SHCORD -- Change Order Number [Generic Edit] Numeric (3)
,'' SHBSC -- Buying Segment Code [UDC (42B BS)] String (10)
,'' SHBCRC -- Currency Code - Base [Generic Edit] String (3)
,'' SHAUFT -- Address Number to use for Tax [UDC (42B UA)] Character (1)
,'' SHAUFI -- Address Number to use for Transportation [UDC (42B UA)] Character (1)
,'' SHOPBO -- OP Business Objective [UDC (34A BO)] String (30)
,'' SHOPTC -- OP Total Cost [Generic Edit] Numeric (15)
,'' SHOPLD -- OP Latest Line Date [Generic Edit] Date (6)
,'' SHOPBK -- OP Number of Backorders [Generic Edit] Numeric (15)
,'' SHOPSB -- OP Number of Substitutes [Generic Edit] Numeric (15)
,'' SHOPPS -- OP Promised Status [Generic Edit] String (30)
,'' SHOPPL -- OP Partial Order Shipment [Generic Edit] Character (1)
,'' SHOPMS -- OP Allow Multi Source [Generic Edit] Character (1)
,'' SHOPSS -- OP Allow Substitutes [Generic Edit] Character (1)
,'' SHOPBA -- OP Allow Backorders [Generic Edit] Character (1)
,'' SHOPLL -- OP Partial Ship Line Items [Generic Edit] Character (1)
,'' SHPRAN8 -- Partner Address Number [Generic Edit] Numeric (8)
,'' SHOPPID -- Opportunity Number [Generic Edit] Numeric (15)
,'' SHSDATTN -- Sold To Attention [Generic Edit] String (50)
,'' SHSPATTN -- Ship To Attention [Generic Edit] String (50)
,'' SHOTIND -- Order Type Indicator [Generic Edit] Character (1)
,'' SHPRCIDLN -- Partner Contact Line Number ID [Generic Edit] Numeric (5)
,'' SHCCIDLN -- Customer Contact Line Number ID [Generic Edit] Numeric (5)
,'' SHSHCCIDLN -- Ship To Cust Contact Line Num ID [Generic Edit] Numeric (5)

FROM

TBD