/*
    F42119 - Sales Order Detail History
    VER0001 -  Tom Sampson
*/

SELECT

 '' SDKCOO -- Order Company (Order Number) [Generic Edit] String (5)
,'' SDDOCO -- Document (Order No Invoice etc.) [Generic Edit] Numeric (8)
,'' SDDCTO -- Order Type [UDC (00 DT)] String (2)
,'' SDLNID -- Line Number [Generic Edit] Numeric (6)
,'' SDSFXO -- Order Suffix [Generic Edit] String (3)
,'' SDMCU -- Business Unit [Generic Edit] String (12)
,'' SDCO -- Company [Generic Edit] String (5)
,'' SDOKCO -- Document Company (Original Order) [Generic Edit] String (5)
,'' SDOORN -- Original Order Number [Generic Edit] String (8)
,'' SDOCTO -- Original Order Type [UDC (00 DT)] String (2)
,'' SDOGNO -- Original Line Number [Generic Edit] Numeric (7)
,'' SDRKCO -- Company - Key (Related Order) [Generic Edit] String (5)
,'' SDRORN -- Related PO/SO/WO Number [Generic Edit] String (8)
,'' SDRCTO -- Related PO/SO/WO Order Type [UDC (00 DT)] String (2)
,'' SDRLLN -- Related PO/SO Line Number [Generic Edit] Numeric (7)
,'' SDDMCT -- Agreement Number - Distribution [Generic Edit] String (12)
,'' SDDMCS -- Agreement Supplement - Distribution [Generic Edit] Numeric (3)
,'' SDAN8 -- Address Number [Generic Edit] Numeric (8)
,'' SDSHAN -- Address Number - Ship To [Generic Edit] Numeric (8)
,'' SDPA8 -- Address Number - Parent [Generic Edit] Numeric (8)
,'' SDDRQJ -- Date - Requested [Generic Edit] Date (6)
,'' SDTRDJ -- Date - Order/Transaction [Generic Edit] Date (6)
,'' SDPDDJ -- Date - Scheduled Pick [Generic Edit] Date (6)
,'' SDADDJ -- Date - Actual Ship Date [Generic Edit] Date (6)
,'' SDIVD -- Date - Invoice [Generic Edit] Date (6)
,'' SDCNDJ -- Date - Cancel [Generic Edit] Date (6)
,'' SDDGL -- Date - For G/L (and Voucher) [Generic Edit] Date (6)
,'' SDRSDJ -- Date - Promised Delivery [Generic Edit] Date (6)
,'' SDPEFJ -- Date - Price Effective Date [Generic Edit] Date (6)
,'' SDPPDJ -- Date - Promised Shipment [Generic Edit] Date (6)
,'' SDVR01 -- Reference [Generic Edit] String (25)
,'' SDVR02 -- Reference 2 [Generic Edit] String (25)
,'' SDITM -- Item Number - Short [Generic Edit] Numeric (8)
,'' SDLITM -- 2nd Item Number [Generic Edit] String (25)
,'' SDAITM -- 3rd Item Number [Generic Edit] String (25)
,'' SDLOCN -- Location [Generic Edit] String (20)
,'' SDLOTN -- Lot/Serial Number [Generic Edit] String (30)
,'' SDFRGD -- From Grade [UDC (40 LG)] String (3)
,'' SDTHGD -- Thru Grade [UDC (40 LG)] String (3)
,'' SDFRMP -- From Potency [Generic Edit] Numeric (7)
,'' SDTHRP -- Thru Potency [Generic Edit] Numeric (7)
,'' SDEXDP -- Days Before Expiration [Generic Edit] Numeric (5)
,'' SDDSC1 -- Description [Generic Edit] String (30)
,'' SDDSC2 -- Description - Line 2 [Generic Edit] String (30)
,'' SDLNTY -- Line Type [Generic Edit] String (2)
,'' SDNXTR -- Status Code - Next [UDC (40 AT)] String (3)
,'' SDLTTR -- Status Code - Last [UDC (40 AT)] String (3)
,'' SDEMCU -- Business Unit - Header [Generic Edit] String (12)
,'' SDRLIT -- Item Number - Related (Kit) [Generic Edit] String (8)
,'' SDKTLN -- Kit Master Line Number [Generic Edit] Numeric (6)
,'' SDCPNT -- Component Line Number [Generic Edit] Numeric (4)
,'' SDRKIT -- Related Kit Component [Generic Edit] Numeric (8)
,'' SDKTP -- Number of Component Per Parent [Generic Edit] Numeric (15)
,'' SDSRP1 -- Sales Catalog Section [UDC (41 S1)] String (3)
,'' SDSRP2 -- Sub Section [UDC (41 S2)] String (3)
,'' SDSRP3 -- Sales Category Code 3 [UDC (41 S3)] String (3)
,'' SDSRP4 -- Sales Category Code 4 [UDC (41 S4)] String (3)
,'' SDSRP5 -- Sales Category Code 5 [UDC (41 S5)] String (3)
,'' SDPRP1 -- Commodity Class [UDC (41 P1)] String (3)
,'' SDPRP2 -- Commodity Sub Class [UDC (41 P2)] String (3)
,'' SDPRP3 -- Supplier Rebate Code [UDC (41 P3)] String (3)
,'' SDPRP4 -- Master Planning Family [UDC (41 P4)] String (3)
,'' SDPRP5 -- Purchasing Category Code 5 [UDC (41 P5)] String (3)
,'' SDUOM -- Unit of Measure as Input [UDC (00 UM)] String (2)
,'' SDUORG -- Units - Order/Transaction Quantity [Generic Edit] Numeric (15)
,'' SDSOQS -- Quantity Shipped [Generic Edit] Numeric (15)
,'' SDSOBK -- Units - Qty Backordered/Held [Generic Edit] Numeric (15)
,'' SDSOCN -- Units - Quantity Canceled/Scrapped [Generic Edit] Numeric (15)
,'' SDSONE -- Units - Future Quantity Committed [Generic Edit] Numeric (15)
,'' SDUOPN -- Units - Open [Generic Edit] Numeric (15)
,'' SDQTYT -- Units - Shipped to Date [Generic Edit] Numeric (15)
,'' SDQRLV -- Units - Relieved [Generic Edit] Numeric (15)
,'' SDCOMM -- Committed (H/S) [UDC (H42 CP)] Character (1)
,'' SDOTQY -- Other Quantity (1/2) [UDC] Character (1)
,'' SDUPRC -- Amount - Price per Unit [Generic Edit] Numeric (15)
,'' SDAEXP -- Amount - Extended Price [Generic Edit] Numeric (15)
,'' SDAOPN -- Amount - Open [Generic Edit] Numeric (15)
,'' SDPROV -- Price Override Code [Generic Edit] Character (1)
,'' SDTPC -- Temporary Price (Y/N) [Generic Edit] Character (1)
,'' SDAPUM -- Unit of Measure - Entered for Unit Price [UDC (00 UM)] String (2)
,'' SDLPRC -- Amount - List Price [Generic Edit] Numeric (15)
,'' SDUNCS -- Amount - Unit Cost [Generic Edit] Numeric (15)
,'' SDECST -- Amount - Extended Cost [Generic Edit] Numeric (15)
,'' SDCSTO -- Cost Override Code [Generic Edit] Character (1)
,'' SDTCST -- Extended Cost - Transfer [Generic Edit] Numeric (15)
,'' SDINMG -- Print Message [UDC (40 PM)] String (10)
,'' SDPTC -- Payment Terms Code [Generic Edit] String (3)
,'' SDRYIN -- Payment Instrument [UDC (00 PY)] Character (1)
,'' SDDTBS -- Based on Date [UDC (42 BD)] Character (1)
,'' SDTRDC -- Discount - Trade [Generic Edit] Numeric (7)
,'' SDFUN2 -- Trade Discount (Old) [Generic Edit] Numeric (15)
,'' SDASN -- Price and Adjustment Schedule [UDC (40 AS)] String (8)
,'' SDPRGR -- Item Price Group [UDC (40 PI)] String (8)
,'' SDCLVL -- Pricing Category Level [Generic Edit] String (3)
,'' SDCADC -- Discount % - Cash [Generic Edit] Numeric (7)
,'' SDKCO -- Document Company [Generic Edit] String (5)
,'' SDDOC -- Document (Voucher Invoice etc.) [Generic Edit] Numeric (8)
,'' SDDCT -- Document Type [UDC (00 DT)] String (2)
,'' SDODOC -- Document - Original [Generic Edit] Numeric (8)
,'' SDODCT -- Document Type - Original [UDC (00 DT)] String (2)
,'' SDOKC -- Document Company - Original [Generic Edit] String (5)
,'' SDPSN -- Pick Slip Number [Generic Edit] Numeric (8)
,'' SDDELN -- Delivery Number [Generic Edit] Numeric (8)
,'' SDTAX1 -- Sales Taxable (Y/N) [UDC (H00 TV)] Character (1)
,'' SDTXA1 -- Tax Rate/Area [Generic Edit] String (10)
,'' SDEXR1 -- Tax Expl Code 1 [UDC (00 EX)] String (2)
,'' SDATXT -- Associated Text [Generic Edit] Character (1)
,'' SDPRIO -- Priority - Processing [UDC (H40 PR)] Character (1)
,'' SDRESL -- Printed Code [Generic Edit] Character (1)
,'' SDBACK -- Backorders Allowed (Y/N) [Generic Edit] Character (1)
,'' SDSBAL -- Substitutes Allowed (Y/N) [Generic Edit] Character (1)
,'' SDAPTS -- Partial Line Shipments Allowed (Y/N) [Generic Edit] Character (1)
,'' SDLOB -- Line of Business [UDC (40 LB)] String (3)
,'' SDEUSE -- End Use [UDC (40 EU)] String (3)
,'' SDDTYS -- Duty Status [UDC (40 DS)] String (2)
,'' SDNTR -- Nature of Transaction [UDC (00 NT)] String (2)
,'' SDVEND -- Primary / Last Supplier Number [Generic Edit] Numeric (8)
,'' SDCARS -- Carrier Number [Generic Edit] Numeric (8)
,'' SDMOT -- Mode of Transport [UDC (00 TM)] String (3)
,'' SDROUT -- Route Code [UDC (42 RT)] String (3)
,'' SDSTOP -- Stop Code [UDC (42 SP)] String (3)
,'' SDZON -- Zone Number [UDC (40 ZN)] String (3)
,'' SDCNID -- Container I.D. [Generic Edit] String (20)
,'' SDFRTH -- Freight Handling Code [UDC (42 FR)] String (3)
,'' SDSHCM -- Shipping Commodity Class [UDC (41 E)] String (3)
,'' SDSHCN -- Shipping Conditions Code [UDC (41 C)] String (3)
,'' SDSERN -- Serial Number - Lot [Generic Edit] String (30)
,'' SDUOM1 -- Unit of Measure - Primary [UDC (00 UM)] String (2)
,'' SDPQOR -- Units - Primary Quantity Ordered [Generic Edit] Numeric (15)
,'' SDUOM2 -- Unit of Measure - Secondary [UDC (00 UM)] String (2)
,'' SDSQOR -- Units - Secondary Quantity Ordered [Generic Edit] Numeric (15)
,'' SDUOM4 -- Unit of Measure - Pricing [UDC (00 UM)] String (2)
,'' SDITWT -- Unit Weight [Generic Edit] Numeric (15)
,'' SDWTUM -- Weight Unit of Measure [UDC (00 UM)] String (2)
,'' SDITVL -- Unit Volume [Generic Edit] Numeric (15)
,'' SDVLUM -- Volume Unit of Measure [UDC (00 UM)] String (2)
,'' SDRPRC -- Reprice (Basket Price) Category [UDC (40 PI)] String (8)
,'' SDORPR -- Order Reprice Category [UDC (40 PI)] String (8)
,'' SDORP -- Order Repriced Indicator [Generic Edit] Character (1)
,'' SDCMGP -- Costing Method - Inventory [Generic Edit] String (2)
,'' SDGLC -- G/L Offset [Generic Edit] String (4)
,'' SDCTRY -- Century [Generic Edit] Numeric (2)
,'' SDFY -- Fiscal Year [Generic Edit] Numeric (2)
,'' SDSO01 -- Inter Branch Sales [Generic Edit] Character (1)
,'' SDSO02 -- On Hand Updated [Generic Edit] Character (1)
,'' SDSO03 -- Configurator Print Flag [Generic Edit] Character (1)
,'' SDSO04 -- Sales Order Status 04 [Generic Edit] Character (1)
,'' SDSO05 -- Substitute Item Indicator [Generic Edit] Character (1)
,'' SDSO06 -- Preference Commitment Indicator [Generic Edit] Character (1)
,'' SDSO07 -- Ship date (PDDJ) overridden [Generic Edit] Character (1)
,'' SDSO08 -- Price Adjustment Line Indicator [Generic Edit] Character (1)
,'' SDSO09 -- Price Adj. History Indicator [Generic Edit] Character (1)
,'' SDSO10 -- Preference Production Allocation [Generic Edit] Character (1)
,'' SDSO11 -- Transfer/Direct Ship/Intercompany Flag [Generic Edit] Character (1)
,'' SDSO12 -- Deferred entries flag [Generic Edit] Character (1)
,'' SDSO13 -- Euro Conversion Status Flag [Generic Edit] Character (1)
,'' SDSO14 -- Sales Order Status 14 [Generic Edit] Character (1)
,'' SDSO15 -- Sales Order Status 15 [Generic Edit] Character (1)
,'' SDACOM -- Apply Commission (Y/N) [Generic Edit] Character (1)
,'' SDCMCG -- Commission Category [Generic Edit] String (8)
,'' SDRCD -- Reason Code [UDC (42 RC)] String (3)
,'' SDGRWT -- Gross Weight [Generic Edit] Numeric (15)
,'' SDGWUM -- Gross Weight Unit of Measure [UDC (00 UM)] String (2)
,'' SDSBL -- Subledger - G/L [Generic Edit] String (8)
,'' SDSBLT -- Subledger Type [UDC (00 ST)] Character (1)
,'' SDLCOD -- Code - Location Tax Status [UDC (46 LT)] String (2)
,'' SDUPC1 -- Price Code 1 [UDC (40 P1)] String (2)
,'' SDUPC2 -- Price Code 2 [UDC (40 P2)] String (2)
,'' SDUPC3 -- Price Code 3 [UDC (40 P3)] String (2)
,'' SDSWMS -- Status - In Warehouse [Generic Edit] Character (1)
,'' SDUNCD -- Work Order Freeze Code [UDC (H00 UN)] Character (1)
,'' SDCRMD -- Send Method [UDC (00 SM)] Character (1)
,'' SDCRCD -- Currency Code - From [Generic Edit] String (3)
,'' SDCRR -- Currency Conversion Rate - Spot Rate [Generic Edit] Numeric (15)
,'' SDFPRC -- Amount - List Price per Unit [Generic Edit] Numeric (15)
,'' SDFUP -- Amount - Foreign Price per Unit [Generic Edit] Numeric (15)
,'' SDFEA -- Amount - Foreign Extended Price [Generic Edit] Numeric (15)
,'' SDFUC -- Amount - Foreign Unit Cost [Generic Edit] Numeric (15)
,'' SDFEC -- Amount - Foreign Extended Cost [Generic Edit] Numeric (15)
,'' SDURCD -- User Reserved Code [Generic Edit] String (2)
,'' SDURDT -- User Reserved Date [Generic Edit] Date (6)
,'' SDURAT -- User Reserved Amount [Generic Edit] Numeric (15)
,'' SDURAB -- User Reserved Number [Generic Edit] Numeric (8)
,'' SDURRF -- User Reserved Reference [Generic Edit] String (15)
,'' SDTORG -- Transaction Originator [Generic Edit] String (10)
,'' SDUSER -- User ID [Generic Edit] String (10)
,'' SDPID -- Program ID [Generic Edit] String (10)
,'' SDJOBN -- Work Station ID [Generic Edit] String (10)
,'' SDUPMJ -- Date - Updated [Generic Edit] Date (6)
,'' SDTDAY -- Time of Day [Generic Edit] Numeric (6)
,'' SDSO16 -- Manufacturing Variance Accounting Flag [Generic Edit] Character (1)
,'' SDSO17 -- Sales Order Status 17 [Generic Edit] Character (1)
,'' SDSO18 -- Sales Order Status 18 [Generic Edit] Character (1)
,'' SDSO19 -- Sales Order Status 19 [Generic Edit] Character (1)
,'' SDSO20 -- Sales Order Status 20 [Generic Edit] Character (1)
,'' SDIR01 -- Integration Reference 01 [Generic Edit] String (30)
,'' SDIR02 -- Integration Reference 02 [Generic Edit] String (30)
,'' SDIR03 -- Integration Reference 03 [Generic Edit] String (30)
,'' SDIR04 -- Integration Reference 04 [Generic Edit] String (30)
,'' SDIR05 -- Integration Reference 05 [Generic Edit] String (30)
,'' SDSOOR -- Source of Order [Generic Edit] Integer (11)
,'' SDVR03 -- Reference [Generic Edit] String (25)
,'' SDDEID -- Demand Unique Key ID [Generic Edit] Numeric (15)
,'' SDPSIG -- Pull Signal [Generic Edit] String (30)
,'' SDRLNU -- Release Number [Generic Edit] String (10)
,'' SDPMDT -- Scheduled Shipment Time [Generic Edit] Numeric (6)
,'' SDRLTM -- Time - Release [Generic Edit] Numeric (6)
,'' SDRLDJ -- Date - Release [Generic Edit] Date (6)
,'' SDDRQT -- Requested Delivery Time [Generic Edit] Numeric (6)
,'' SDADTM -- Actual Shipment Time [Generic Edit] Numeric (6)
,'' SDOPTT -- Time - Original Promised Delivery [Generic Edit] Numeric (6)
,'' SDPDTT -- Time - Scheduled Pick [Generic Edit] Numeric (6)
,'' SDPSTM -- Time - Future Time 2 [Generic Edit] Numeric (6)
,'' SDXDCK -- Cross-Docking Flag [Generic Edit] Character (1)
,'' SDXPTY -- Cross Docking Priority for Sales Orders [Generic Edit] Numeric (15)
,'' SDDUAL -- Dual Unit Of Measure Item [Generic Edit] Character (1)
,'' SDBSC -- Buying Segment Code [UDC (42B BS)] String (10)
,'' SDCBSC -- Current Buying Segment Code [UDC (42B BS)] String (10)
,'' SDCORD -- Change Order Number [Generic Edit] Numeric (3)
,'' SDDVAN -- Address Number - Deliver To [Generic Edit] Numeric (8)
,'' SDPEND -- Pending Approval Flag [Generic Edit] Character (1)
,'' SDRFRV -- Revision Reason [UDC (42 RR)] String (3)
,'' SDMCLN -- Matrix Control Line Number [Generic Edit] Numeric (6)
,'' SDSHPN -- Shipment Number [Generic Edit] Numeric (8)
,'' SDRSDT -- Promised Delivery Time [Generic Edit] Numeric (6)
,'' SDPRJM -- Project Number [Generic Edit] Numeric (8)
,'' SDOSEQ -- Sequence Number [Generic Edit] Numeric (4)
,'' SDMERL -- Item Revision Level [Generic Edit] String (3)
,'' SDHOLD -- Hold Orders Code [UDC (42 HC)] String (2)
,'' SDHDBU -- Business Unit - Header [Generic Edit] String (12)
,'' SDDMBU -- Business Unit - Demand [Generic Edit] String (12)
,'' SDBCRC -- Currency Code - Base [Generic Edit] String (3)
,'' SDODLN -- Document Line Number - Original [Generic Edit] Numeric (7)
,'' SDOPDJ -- Date - Original Promised Delivery [Generic Edit] Date (6)
,'' SDXKCO -- Cross Dock Order Company (Order Number) [Generic Edit] String (5)
,'' SDXORN -- Cross Dock Order No [Generic Edit] Numeric (8)
,'' SDXCTO -- Cross Dock Order Type [UDC (00 DT)] String (2)
,'' SDXLLN -- Cross Dock Line Number [Generic Edit] Numeric (6)
,'' SDXSFX -- Cross Dock Order Suffix [Generic Edit] String (3)
,'' SDPOE -- Port of Entry or Exit [UDC (40 PE)] String (6)
,'' SDPMTO -- Payment Terms Override Code [Generic Edit] Character (1)
,'' SDANBY -- Buyer Number [Generic Edit] Numeric (8)
,'' SDPMTN -- Promotion ID [Generic Edit] String (12)
,'' SDNUMB -- Asset Item Number [Generic Edit] Numeric (8)
,'' SDAAID -- Parent Number [Generic Edit] Numeric (8)
,'' SDSPATTN -- Ship To Attention [Generic Edit] String (50)
,'' SDPRAN8 -- Partner Address Number [Generic Edit] Numeric (8)
,'' SDPRCIDLN -- Partner Contact Line Number ID [Generic Edit] Numeric (5)
,'' SDCCIDLN -- Customer Contact Line Number ID [Generic Edit] Numeric (5)
,'' SDSHCCIDLN -- Ship To Cust Contact Line Num ID [Generic Edit] Numeric (5)
,'' SDOPPID -- Opportunity Number [Generic Edit] Numeric (15)
,'' SDOSTP -- Organization Structure Type [UDC (01 TS)] String (3)
,'' SDUKID -- Unique Key ID (Internal) [Generic Edit] Numeric (15)
,'' SDCATNM -- Catalog Name [Generic Edit] String (30)
,'' SDALLOC -- Allocation Process Flag [Generic Edit] Character (1)
,'' SDFULPID -- Fulfillment Plan ID [Generic Edit] Integer (11)
,'' SDALLSTS -- Allocation Status Number [UDC (42 AS)] String (30)
,'' SDOSCORE -- Sales Order Score [Generic Edit] Numeric (15)
,'' SDOSCOREO -- Order Score Override [Generic Edit] Character (1)
,'' SDCMCO -- Customer Master Company [Generic Edit] String (5)
,'' SDKITID -- Kit Identifier [Generic Edit] Numeric (15)
,'' SDKITAMTDOM -- Accumulated Amount Invoiced (Domestic) [Generic Edit] Numeric (15)
,'' SDKITAMTFOR -- Accumulated Amount Invoiced (Foreign) [Generic Edit] Numeric (15)
,'' SDKITDIRTY -- Kit Component Dirty Flag [Generic Edit] Character (1)
,'' SDOCITT -- OC In-Transit Flag [Generic Edit] Character (1)
,'' SDOCCARDNO -- OC Kanban Card No [Generic Edit] Numeric (8)
,'' SDPMPN -- Production Number [Generic Edit] String (30)
,'' SDPNS -- Production Number Short [Generic Edit] Numeric (10)

FROM

TBD