CREATE VIEW _COM_BASE AS

SELECT ORDER_REF.NEW_ID AS SHDOCO -- Document (Order No Invoice etc.) (Numeric) Generic Edit [8]
	,'SO' AS SHDCTO  -- Order Type (String) UDC (00 DT) [2]
	,'00020' AS SHKCOO -- Order Company (Order Number) (String) Generic Edit [5]
	,REPS1.ABAN8 AS SHSLSM -- Salesperson 01 (Numeric) Generic Edit [8]
	,CASE 
		WHEN REPS2.ABAN8 IS NULL
			THEN CAST(ISNULL(LINE.COMMISSION_PCT, 0) * 1000 AS INTEGER)
		ELSE CAST(ISNULL(LINE.COMMISSION_PCT * (1 - SHARE.SHARE_PERCENT), 0) * 1000 AS INTEGER)
		END AS SHSLCM -- Salesperson Commission 001 (Numeric) Generic Edit [7]
	,'0' AS SHFCA -- Flat Commission Amount (Numeric) Generic Edit [15]
	,'0' AS SHAPUN -- Amount - Per Unit (Numeric) Generic Edit [15]
	,'I' AS SHCCTY -- Commission Code Type (Character) UDC (H42 CC) [1]
	,ISNULL(SHARE.SHARE_PERCENT, 0) AS COM_SHARE
	,CO.SALESREP_ID AS REP1_OLD_ID
	,REPS1.ABAN8 AS REP1_NEW_ID
	,SHARE.SHARE_SALESREP_ID AS REP2_OLD_ID
	,REPS2.ABAN8 AS REP2_NEW_ID
	,CASE
		WHEN SHARE.SHARE_PERCENT IS NULL
		THEN (LINE.COMMISSION_PCT/100) * ISNULL(LINE.TOTAL_AMT_SHIPPED,0)
		ELSE ((LINE.COMMISSION_PCT/100) * (1 - SHARE.SHARE_PERCENT/100)) * ISNULL(LINE.TOTAL_AMT_SHIPPED,0)
	 END LINE_COM
	,CASE
		WHEN SHARE.SHARE_PERCENT IS NOT NULL
		THEN ((LINE.COMMISSION_PCT/100) * (SHARE.SHARE_PERCENT/100)) * ISNULL(LINE.TOTAL_AMT_SHIPPED,0)
		ELSE 0
	 END LINE_SHARE
	 ,LINE.TOTAL_AMT_SHIPPED TOTAL_AMT_SHIPPED
	
FROM dbo.CUSTOMER_ORDER AS CO
LEFT OUTER JOIN dbo._REPS AS REPS1
	ON 'BC_' + CO.SALESREP_ID = REPS1.ABALKY
LEFT OUTER JOIN dbo.CUST_ORDER_LINE AS LINE
	ON LINE.CUST_ORDER_ID = CO.ID
INNER JOIN (
	SELECT DISTINCT NEW_ID
		,OLD_ID
	FROM dbo._ORDER_REF
	) AS ORDER_REF
	ON LINE.CUST_ORDER_ID = ORDER_REF.OLD_ID
LEFT OUTER JOIN dbo.CUST_ORDER_SHARE AS SHARE
	ON SHARE.CUST_ORDER_ID = LINE.CUST_ORDER_ID
LEFT OUTER JOIN dbo._REPS AS REPS2
	ON 'BC_' + SHARE.SHARE_SALESREP_ID = REPS2.ABALKY
