/* CS union

*/
SELECT SHIPTO.SZEDUS
	,SHIPTO.SZEDBT
	,(
		ROW_NUMBER() OVER (
			ORDER BY SHIPTO.SORT
			)
		) + 76000 SZEDTN
	,SHIPTO.SZEDLN
	,SHIPTO.SZEDCT
	,SHIPTO.SZTYTN
	,SHIPTO.SZEDFT
	,SHIPTO.SZEDDT
	,SHIPTO.SZDRIN
	,SHIPTO.SZEDDL
	,SHIPTO.SZEDSP
	,SHIPTO.SZPNID
	,SHIPTO.SZTNAC
	,(
		ROW_NUMBER() OVER (
			ORDER BY SHIPTO.SORT
			)
		) + 76000 SZAN8
	,SHIPTO.SZALKY
	,SHIPTO.SZTAX
	,SHIPTO.SZALPH
	,SHIPTO.SZDC
	,SHIPTO.SZMCU
	,SHIPTO.SZSIC
	,SHIPTO.SZLNGP
	,SHIPTO.SZAT1
	,SHIPTO.SZCM
	,SHIPTO.SZTAXC
	,SHIPTO.SZAT2
	,SHIPTO.SZAT3
	,SHIPTO.SZAT4
	,SHIPTO.SZATR
	,SHIPTO.SZAT5
	,SHIPTO.SZATP
	,SHIPTO.SZATPR
	,SHIPTO.SZAB3
	,SHIPTO.SZATE
	,SHIPTO.SZSBLI
	,SHIPTO.SZEFTB
	,BILLTO.SZAN8 SZAN81
	,SHIPTO.SZAN82
	,SHIPTO.SZAN83
	,SHIPTO.SZAN84
	,SHIPTO.SZAN86
	,SHIPTO.SZAN85
	,SHIPTO.SZAC01
	,SHIPTO.SZAC02
	,SHIPTO.SZAC03
	,SHIPTO.SZAC04
	,SHIPTO.SZAC05
	,SHIPTO.SZAC06
	,SHIPTO.SZAC07
	,SHIPTO.SZAC08
	,SHIPTO.SZAC09
	,SHIPTO.SZAC10
	,SHIPTO.SZAC11
	,SHIPTO.SZAC12
	,SHIPTO.SZAC13
	,SHIPTO.SZAC14
	,SHIPTO.SZAC15
	,SHIPTO.SZAC16
	,SHIPTO.SZAC17
	,SHIPTO.SZAC18
	,SHIPTO.SZAC19
	,SHIPTO.SZAC20
	,SHIPTO.SZAC21
	,SHIPTO.SZAC22
	,SHIPTO.SZAC23
	,SHIPTO.SZAC24
	,SHIPTO.SZAC25
	,SHIPTO.SZAC26
	,SHIPTO.SZAC27
	,SHIPTO.SZAC28
	,SHIPTO.SZAC29
	,SHIPTO.SZAC30
	,SHIPTO.SZGLBA
	,SHIPTO.SZPTI
	,SHIPTO.SZPDI
	,SHIPTO.SZMSGA
	,SHIPTO.SZRMK
	,SHIPTO.SZTXCT
	,SHIPTO.SZTX2
	,SHIPTO.SZALP1
	,SHIPTO.SZURCD
	,SHIPTO.SZURDT
	,SHIPTO.SZURAT
	,SHIPTO.SZURAB
	,SHIPTO.SZURRF
	,SHIPTO.SZMLNM
	,SHIPTO.SZMLN1
	,SHIPTO.SZADD1
	,SHIPTO.SZADD2
	,SHIPTO.SZADD3
	,SHIPTO.SZADD4
	,SHIPTO.SZADDZ
	,SHIPTO.SZCTY1
	,SHIPTO.SZCTR
	,SHIPTO.SZADDS
	,SHIPTO.SZCOUN
	,SHIPTO.SZAR1
	,SHIPTO.SZPH1
	,SHIPTO.SZPHT1
	,SHIPTO.SZAR2
	,SHIPTO.SZPH2
	,SHIPTO.SZPHT2
	,SHIPTO.SZTORG
	,SHIPTO.SZUSER
	,SHIPTO.SZPID
	,SHIPTO.SZJOBN
	,SHIPTO.SZUPMJ
	,SHIPTO.SZTDAY
	,SHIPTO.SZUPMT
	,SHIPTO.SZPRGF
	,SHIPTO.SZSCCLTP
	,SHIPTO.SZPA8
	,SHIPTO.SZTICKER
	,SHIPTO.SZEXCHG
	,SHIPTO.SZDUNS
	,SHIPTO.SZCLASS01
	,SHIPTO.SZCLASS02
	,SHIPTO.SZCLASS03
	,SHIPTO.SZCLASS04
	,SHIPTO.SZCLASS05
	,SHIPTO.SZNOE
	,SHIPTO.SZGROWTHR
	,SHIPTO.SZYEARSTAR
	,SHIPTO.SZAEMPGP
	,SHIPTO.SZACTIN
	,SHIPTO.SZREVRNG
FROM (
	SELECT DISTINCT 'JDE' SZEDUS
		,'BAL0003' SZEDBT
		,'' SZEDTN /* primary key edi*/
		,0 SZEDLN
		,'' SZEDCT
		,'JDEAB' SZTYTN
		,'' SZEDFT
		,'' SZEDDT
		,'' SZDRIN
		,'' SZEDDL
		,'N' SZEDSP
		,'' SZPNID
		,'A' SZTNAC
		,'' SZAN8 /* primary key*/
		,'BC_' + LTRIM(RTRIM(CUSTOMER.ID)) + '_' + LTRIM(RTRIM(CAST(CUST_ADDRESS.ADDR_NO AS CHAR))) SZALKY
		,'' SZTAX
		,LEFT(LTRIM(RTRIM(REPLACE(REPLACE(CUST_ADDRESS.NAME, '.', ''), ',', ''))), 40) SZALPH
		,'' SZDC
		,'          20' SZMCU
		,'' SZSIC
		,'' SZLNGP
		,'CS' SZAT1
		,'' SZCM
		,'2' SZTAXC
		,'N' SZAT2
		,'N' SZAT3
		,'N' SZAT4
		,'Y' SZATR
		,'N' SZAT5
		,'N' SZATP
		,'N' SZATPR
		,'N' SZAB3
		,'N' SZATE
		,'' SZSBLI
		,dbo.JDEJulian(GETDATE()) SZEFTB /* JDE julian today*/
		,'' SZAN81
		,'' SZAN82
		,'' SZAN83
		,'' SZAN84
		,'' SZAN86
		,'' SZAN85
		,'' SZAC01
		,'' SZAC02
		,'' SZAC03
		,'' SZAC04
		,'' SZAC05
		,'' SZAC06
		,'' SZAC07
		,'' SZAC08
		,'' SZAC09
		,'' SZAC10
		,'' SZAC11
		,'' SZAC12
		,'' SZAC13
		,'' SZAC14
		,'' SZAC15
		,'' SZAC16
		,'' SZAC17
		,'' SZAC18
		,'' SZAC19
		,'' SZAC20
		,'' SZAC21
		,'' SZAC22
		,'' SZAC23
		,'' SZAC24
		,'' SZAC25
		,'' SZAC26
		,'' SZAC27
		,'' SZAC28
		,'' SZAC29
		,'' SZAC30
		,'' SZGLBA
		,0 SZPTI
		,'0' SZPDI
		,'' SZMSGA
		,'' SZRMK
		,'' SZTXCT
		,'' SZTX2
		,'' SZALP1
		,'' SZURCD
		,'0' SZURDT
		,0 SZURAT
		,0 SZURAB
		,CUST_ADDRESS.SHIPTO_ID SZURRF /* for CS only, old CUST_ADDRESS.SHIPTO_ID*/
		,'' SZMLNM
		,'' SZMLN1
		,CASE 
			WHEN CUST_ADDRESS.ADDR_1 IS NOT NULL /* Only use old ADDR_1 if it looks like a street address*/
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <= '9'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '%'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '#'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '('
				AND LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)) <> ''
				THEN LTRIM(RTRIM(LEFT(ISNULL(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), ''), 40)))
			WHEN CUST_ADDRESS.ADDR_2 IS NOT NULL /* Otherwise old ADDR_2 may work*/
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 1) <= '9'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 1) <> '%'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 1) <> '#'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 1) <> '('
				AND CUST_ADDRESS.ADDR_2 NOT LIKE '%@%'
				THEN LTRIM(RTRIM(LEFT(ISNULL(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), ''), 40)))
			ELSE ''
			END SZADD1
		,CASE 
			WHEN CUST_ADDRESS.ADDR_1 IS NOT NULL /* If old ADDR_1 is new ADDR1, check ADDR2, only use it if it looks legit*/
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <= '9'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '%'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '#'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '('
				AND LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)) <> ''
				AND (
					LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 3) = 'STE'
					OR LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 5) = 'SUITE'
					OR LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 3) = '1ST'
					OR LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 4) = 'BLDG'
					OR LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 8) = 'BUILDING'
					)
				THEN LTRIM(RTRIM(LEFT(ISNULL(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), ''), 40)))
			ELSE ''
			END SZADD2
		,'' SZADD3
		,'' SZADD4
		,CASE 
			WHEN LEN(CUST_ADDRESS.ZIPCODE) <= 12
				THEN LTRIM(RTRIM(CUST_ADDRESS.ZIPCODE))
			ELSE ''
			END SZADDZ
		,CASE 
			WHEN LEN(CUST_ADDRESS.CITY) <= 25
				THEN LTRIM(RTRIM(CUST_ADDRESS.CITY))
			ELSE ''
			END SZCTY1
		,'US' SZCTR
		,CASE 
			WHEN LEN(CUST_ADDRESS.STATE) = 2
				THEN CUST_ADDRESS.STATE
			ELSE ''
			END SZADDS
		,'' SZCOUN
		,CASE 
			WHEN LEFT(REPLACE(CUST_ADDRESS.COUNTRY, '-', ''), 3) IS NOT NULL
				AND LEFT(REPLACE(CUST_ADDRESS.COUNTRY, '-', ''), 3) <> ''
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.COUNTRY)), 1) <= '9'
				THEN LEFT(REPLACE(CUST_ADDRESS.COUNTRY, '-', ''), 3)
			ELSE ''
			END SZAR1
		,CASE 
			WHEN CUST_ADDRESS.COUNTRY IS NOT NULL
				AND LEFT(RIGHT(LEFT(REPLACE(REPLACE(REPLACE(CUST_ADDRESS.COUNTRY, '+', ''), ' ', ''), '-', ''), 10), 7), 3) + '-' + RIGHT(RIGHT(LEFT(REPLACE(REPLACE(REPLACE(CUST_ADDRESS.COUNTRY, '+', ''), ' ', ''), '-', ''), 10), 7), 4) <> ''
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.COUNTRY)), 1) <= '9'
				THEN LEFT(RIGHT(LEFT(REPLACE(REPLACE(REPLACE(CUST_ADDRESS.COUNTRY, '+', ''), ' ', ''), '-', ''), 10), 7), 3) + '-' + RIGHT(RIGHT(LEFT(REPLACE(REPLACE(REPLACE(CUST_ADDRESS.COUNTRY, '+', ''), ' ', ''), '-', ''), 10), 7), 4)
			ELSE ''
			END SZPH1
		,'' SZPHT1
		,'' SZAR2
		,'' SZPH2
		,'' SZPHT2
		,'' SZTORG
		,'TSAMPSON' SZUSER
		,'Import' SZPID
		,'' SZJOBN
		,dbo.JDEJulian(GETDATE()) SZUPMJ
		,'' SZTDAY
		,'' SZUPMT
		,'' SZPRGF
		,'' SZSCCLTP
		,'' SZPA8 /* This is the CB ref, if CSB or CB this is NULL*/
		,'' SZTICKER
		,'' SZEXCHG
		,'' SZDUNS
		,'' SZCLASS01
		,'' SZCLASS02
		,'' SZCLASS03
		,'' SZCLASS04
		,'' SZCLASS05
		,'' SZNOE
		,'' SZGROWTHR
		,'' SZYEARSTAR
		,'' SZAEMPGP
		,'' SZACTIN
		,'' SZREVRNG
		,CUST_ADDRESS.ROWID SORT
		,CUST_ADDRESS.CUSTOMER_ID CUSTOMER_ID
	FROM CUST_ADDRESS CUST_ADDRESS
	JOIN CUSTOMER CUSTOMER /* Bill To Addresses*/ ON CUSTOMER.ID = CUST_ADDRESS.CUSTOMER_ID
		AND CUST_ADDRESS.ADDR_NO = 1
	JOIN _CSB_REF$ CSB_REF ON CUST_ADDRESS.CUSTOMER_ID = CSB_REF.CUSTOMER_ID
	LEFT JOIN (
		SELECT DISTINCT A.CUSTOMER_ID
		FROM CUST_ADDRESS A
		WHERE A.ADDR_NO = 1
		) CB_LIST ON CUST_ADDRESS.CUSTOMER_ID = CB_LIST.CUSTOMER_ID
	JOIN _BILLTO BILLTO ON 'BC_' + CUST_ADDRESS.CUSTOMER_ID = BILLTO.SZALKY
	WHERE CB_LIST.CUSTOMER_ID IS NOT NULL
	
	UNION
	
	SELECT DISTINCT 'JDE' SZEDUS
		,'BAL0004' SZEDBT
		,CAST(105000 + CUST_ADDRESS.ROWID AS INT) SZEDTN /* primary key edi*/
		,0 SZEDLN
		,'' SZEDCT
		,'JDEAB' SZTYTN
		,'' SZEDFT
		,'' SZEDDT
		,'' SZDRIN
		,'' SZEDDL
		,'N' SZEDSP
		,'' SZPNID
		,'A' SZTNAC
		,CAST(105000 + CUST_ADDRESS.ROWID AS INT) SZAN8 /* primary key*/
		,'BC_' + LTRIM(RTRIM(CUSTOMER.ID)) + '_' + LTRIM(RTRIM(CAST(CUST_ADDRESS.ADDR_NO AS CHAR))) SZALKY
		,'' SZTAX
		,LEFT(LTRIM(RTRIM(REPLACE(REPLACE(CUST_ADDRESS.NAME, '.', ''), ',', ''))), 40) SZALPH
		,'' SZDC
		,'          20' SZMCU
		,'' SZSIC
		,'' SZLNGP
		,'CS' SZAT1
		,'' SZCM
		,'2' SZTAXC
		,'N' SZAT2
		,'N' SZAT3
		,'N' SZAT4
		,'Y' SZATR
		,'N' SZAT5
		,'N' SZATP
		,'N' SZATPR
		,'N' SZAB3
		,'N' SZATE
		,'' SZSBLI
		,dbo.JDEJulian(GETDATE()) SZEFTB /* JDE julian today*/
		,'' SZAN81 /* lookup billTo id*/
		,'' SZAN82
		,'' SZAN83
		,'' SZAN84
		,'' SZAN86
		,'' SZAN85
		,'' SZAC01
		,'' SZAC02
		,'' SZAC03
		,'' SZAC04
		,'' SZAC05
		,'' SZAC06
		,'' SZAC07
		,'' SZAC08
		,'' SZAC09
		,'' SZAC10
		,'' SZAC11
		,'' SZAC12
		,'' SZAC13
		,'' SZAC14
		,'' SZAC15
		,'' SZAC16
		,'' SZAC17
		,'' SZAC18
		,'' SZAC19
		,'' SZAC20
		,'' SZAC21
		,'' SZAC22
		,'' SZAC23
		,'' SZAC24
		,'' SZAC25
		,'' SZAC26
		,'' SZAC27
		,'' SZAC28
		,'' SZAC29
		,'' SZAC30
		,'' SZGLBA
		,0 SZPTI
		,'0' SZPDI
		,'' SZMSGA
		,'' SZRMK
		,'' SZTXCT
		,'' SZTX2
		,'' SZALP1
		,'' SZURCD
		,'0' SZURDT
		,0 SZURAT
		,0 SZURAB
		,LEFT(LTRIM(RTRIM(CUST_ADDRESS.SHIPTO_ID)), 15) SZURRF /* for CS only, old CUST_ADDRESS.SHIPTO_ID*/
		,'' SZMLNM
		,'' SZMLN1
		,CASE 
			WHEN CUST_ADDRESS.ADDR_1 IS NOT NULL /* Only use old ADDR_1 if it looks like a street address*/
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <= '9'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '%'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '#'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '('
				AND LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)) <> ''
				THEN LTRIM(RTRIM(LEFT(ISNULL(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), ''), 40)))
			WHEN CUST_ADDRESS.ADDR_2 IS NOT NULL /* Otherwise old ADDR_2 may work*/
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 1) <= '9'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 1) <> '%'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 1) <> '#'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 1) <> '('
				AND CUST_ADDRESS.ADDR_2 NOT LIKE '%@%'
				THEN LTRIM(RTRIM(LEFT(ISNULL(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), ''), 40)))
			ELSE ''
			END SZADD1
		,CASE 
			WHEN CUST_ADDRESS.ADDR_1 IS NOT NULL /* If old ADDR_1 is new ADDR1, check ADDR2, only use it if it looks legit*/
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <= '9'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '%'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '#'
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)), 1) <> '('
				AND LTRIM(RTRIM(CUST_ADDRESS.ADDR_1)) <> ''
				AND (
					LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 3) = 'STE'
					OR LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 5) = 'SUITE'
					OR LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 3) = '1ST'
					OR LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 4) = 'BLDG'
					OR LEFT(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), 8) = 'BUILDING'
					)
				THEN LTRIM(RTRIM(LEFT(ISNULL(LTRIM(RTRIM(CUST_ADDRESS.ADDR_2)), ''), 40)))
			ELSE ''
			END SZADD2
		,'' SZADD3
		,'' SZADD4
		,CASE 
			WHEN LEN(CUST_ADDRESS.ZIPCODE) <= 12
				THEN LTRIM(RTRIM(CUST_ADDRESS.ZIPCODE))
			ELSE ''
			END SZADDZ
		,CASE 
			WHEN LEN(CUST_ADDRESS.CITY) <= 25
				THEN LTRIM(RTRIM(CUST_ADDRESS.CITY))
			ELSE ''
			END SZCTY1
		,'US' SZCTR
		,CASE 
			WHEN LEN(LTRIM(RTRIM(CUST_ADDRESS.STATE))) = 2
				THEN LTRIM(RTRIM(CUST_ADDRESS.STATE))
			ELSE ''
			END SZADDS
		,'' SZCOUN
		,CASE 
			WHEN LEFT(REPLACE(CUST_ADDRESS.COUNTRY, '-', ''), 3) IS NOT NULL
				AND LEFT(REPLACE(CUST_ADDRESS.COUNTRY, '-', ''), 3) <> ''
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.COUNTRY)), 1) <= '9'
				THEN LEFT(REPLACE(CUST_ADDRESS.COUNTRY, '-', ''), 3)
			ELSE ''
			END SZAR1
		,CASE 
			WHEN CUST_ADDRESS.COUNTRY IS NOT NULL
				AND LEFT(RIGHT(LEFT(REPLACE(REPLACE(REPLACE(CUST_ADDRESS.COUNTRY, '+', ''), ' ', ''), '-', ''), 10), 7), 3) + '-' + RIGHT(RIGHT(LEFT(REPLACE(REPLACE(REPLACE(CUST_ADDRESS.COUNTRY, '+', ''), ' ', ''), '-', ''), 10), 7), 4) <> ''
				AND LEFT(LTRIM(RTRIM(CUST_ADDRESS.COUNTRY)), 1) <= '9'
				THEN LEFT(RIGHT(LEFT(REPLACE(REPLACE(REPLACE(CUST_ADDRESS.COUNTRY, '+', ''), ' ', ''), '-', ''), 10), 7), 3) + '-' + RIGHT(RIGHT(LEFT(REPLACE(REPLACE(REPLACE(CUST_ADDRESS.COUNTRY, '+', ''), ' ', ''), '-', ''), 10), 7), 4)
			ELSE ''
			END SZPH1
		,'' SZPHT1
		,'' SZAR2
		,'' SZPH2
		,'' SZPHT2
		,'' SZTORG
		,'TSAMPSON' SZUSER
		,'Import' SZPID
		,'' SZJOBN
		,dbo.JDEJulian(GETDATE()) SZUPMJ
		,'' SZTDAY
		,'' SZUPMT
		,'' SZPRGF
		,'' SZSCCLTP
		,'' SZPA8
		,'' SZTICKER
		,'' SZEXCHG
		,'' SZDUNS
		,'' SZCLASS01
		,'' SZCLASS02
		,'' SZCLASS03
		,'' SZCLASS04
		,'' SZCLASS05
		,'' SZNOE
		,'' SZGROWTHR
		,'' SZYEARSTAR
		,'' SZAEMPGP
		,'' SZACTIN
		,'' SZREVRNG
		,CUST_ADDRESS.ROWID SORT
		,CUST_ADDRESS.CUSTOMER_ID CUSTOMER_ID
	FROM CUST_ADDRESS CUST_ADDRESS
	JOIN CUSTOMER_ORDER ORDERS ON CUST_ADDRESS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
		AND CUST_ADDRESS.ADDR_NO = ORDERS.SHIP_TO_ADDR_NO
		AND ORDERS.SHIP_TO_ADDR_NO > 1
	LEFT JOIN CUSTOMER CUSTOMER ON CUST_ADDRESS.CUSTOMER_ID = CUSTOMER.ID
	WHERE ORDERS.ORDER_DATE IS NOT NULL
	) SHIPTO
LEFT JOIN CUSTOMER CUSTOMER ON SHIPTO.CUSTOMER_ID = CUSTOMER.ID
JOIN _BILLTO BILLTO ON 'BC_' + CUSTOMER.ID = BILLTO.SZALKY