


 ''			SZEDUS -- EDI - User ID String(10)
,''			SZEDBT -- EDI - Batch Number String(15)
,''			SZEDTN -- EDI - Transaction Number String(22)
,''			SZEDLN -- EDI - Line Number Numeric(7)
,''			SZEDCT -- EDI - Document Type String(2)
,''			SZTYTN -- Type - Transaction String(8)
,''			SZEDFT -- EDI - Translation Format String(10)
,''			SZEDDT -- EDI - Transmission Date Date(6)
,''			SZDRIN -- Direction Indicator Character(1)
,''			SZEDDL -- EDI - Detail Lines Processed Numeric(5)
,''			SZEDSP -- EDI - Successfully Processed Character(1)
,''			SZPNID -- Trading Partner ID String(15)
,''			SZTNAC -- Transaction Action String(2)
,''			SZAN8 -- Address Number Numeric(8)
,''			SZALKY -- Long Address Number String(20)
,''			SZTAX -- Tax ID String(20)
,''			SZALPH -- Name - Alpha String(40)
,''			SZDC -- Description - Compressed String(40)
,''			SZMCU -- Business Unit String(12)
,''			SZSIC -- Industry Classification Code String(10)
,''			SZLNGP -- Language String(2)
,''			SZAT1 -- Search Type String(3)
,''			SZCM -- Credit Message String(2)
,''			SZTAXC -- Person/Corporation Code Character(1)
,''			SZAT2 -- AR/AP Netting Indicator Character(1)
,''			SZAT3 -- HRM Records Exist Character(1)
,''			SZAT4 -- Address Type - 4 Character(1)
,''			SZATR -- Address Type - Receivables Character(1)
,''			SZAT5 -- Address Type - 5 Character(1)
,''			SZATP -- Address Type - Payables Character(1)
,''			SZATPR -- Address Type - Code Purchaser Character(1)
,''			SZAB3 -- Address Book - MiscellaneousCode(future) Character(1)
,''			SZATE -- Address Type - Employee Character(1)
,''			SZSBLI -- Subledger Inactive Code Character(1)
,''			SZEFTB -- Date - Beginning Effective Date(6)
,''			SZAN81 -- Address Number - 1st Numeric(8)
,''			SZAN82 -- Address Number - 2nd Numeric(8)
,''			SZAN83 -- Address Number - 3rd Numeric(8)
,''			SZAN84 -- Address Number - 4th Numeric(8)
,''			SZAN86 -- Address Number - 5th Numeric(8)
,''			SZAN85 -- Factor/Special Payee Numeric(8)
,''			SZAC01 -- Category Code - Address Book 01 String(3)
,''			SZAC02 -- Category Code - Address Book 02 String(3)
,''			SZAC03 -- Category Code - Address Book 03 String(3)
,''			SZAC04 -- Category Code - Address Book 04 String(3)
,''			SZAC05 -- Category Code - Address Book 05 String(3)
,''			SZAC06 -- Category Code - Address Book 06 String(3)
,''			SZAC07 -- Category Code - Address Book 07 String(3)
,''			SZAC08 -- Category Code - Address Book 08 String(3)
,''			SZAC09 -- Category Code - Address Book 09 String(3)
,''			SZAC10 -- Category Code - Address Book 10 String(3)
,''			SZAC11 -- Sales Region String(3)
,''			SZAC12 -- Category Code - Address Book 12 String(3)
,''			SZAC13 -- Category Code - Address Book 13 String(3)
,''			SZAC14 -- Category Code - Address Book 14 String(3)
,''			SZAC15 -- Category Code - Address Book 15 String(3)
,''			SZAC16 -- Category Code - Address Book 16 String(3)
,''			SZAC17 -- Category Code - Address Book 17 String(3)
,''			SZAC18 -- Category Code - Address Book 18 String(3)
,''			SZAC19 -- Category Code - Address Book 19 String(3)
,''			SZAC20 -- Category Code - Address Book 20 String(3)
,''			SZAC21 -- Category Code - Address Book 21 String(3)
,''			SZAC22 -- Category Code - Address Book 22 String(3)
,''			SZAC23 -- Category Code - Address Book 23 String(3)
,''			SZAC24 -- Category Code - Address Book 24 String(3)
,''			SZAC25 -- Category Code - Address Book 25 String(3)
,''			SZAC26 -- Category Code - Address Book 26 String(3)
,''			SZAC27 -- Category Code - Address Book 27 String(3)
,''			SZAC28 -- Category Code - Address Book 28 String(3)
,''			SZAC29 -- Category Code - Address Book 29 String(3)
,''			SZAC30 -- Category Code - Address Book 30 String(3)
,''			SZGLBA -- G/L Bank Account String(8)
,''			SZPTI -- Time - Scheduled In Numeric(6)
,''			SZPDI -- Date - Scheduled In Date(6)
,''			SZMSGA -- Action - Message Control Character(1)
,''			SZRMK -- Name - Remark String(30)
,''			SZTXCT -- Certificate Tax Exemption String(20)
,''			SZTX2 -- Tax ID - Additional - Individual String(20)
,''			SZALP1 -- Secondary Alpha Name String(40)
,''			SZURCD -- User Reserved Code String(2)
,''			SZURDT -- User Reserved Date Date(6)
,''			SZURAT -- User Reserved Amount Numeric(15)
,''			SZURAB -- User Reserved Number Numeric(8)
,''			SZURRF -- User Reserved Reference String(15)
,''			SZMLNM -- Name - Mailing String(40)
,''			SZMLN1 -- Secondary Mailing Name String(40)
,''			SZADD1 -- Address Line 1 String(40)
,''			SZADD2 -- Address Line 2 String(40)
,''			SZADD3 -- Address Line 3 String(40)
,''			SZADD4 -- Address Line 4 String(40)
,''			SZADDZ -- Postal Code String(12)
,''			SZCTY1 -- City String(25)
,''			SZCTR -- Country String(3)
,''			SZADDS -- State String(3)
,''			SZCOUN -- County String(25)
,''			SZAR1 -- Phone Prefix String(6)
,''			SZPH1 -- Phone Number String(20)
,''			SZPHT1 -- Phone Number Type 1 String(4)
,''			SZAR2 -- Phone Prefix 2 String(6)
,''			SZPH2 -- Phone Number 2 String(20)
,''			SZPHT2 -- Phone Number Type 2 String(4)
,''			SZTORG -- Transaction Originator String(10)
,''			SZUSER -- User ID String(10)
,''			SZPID -- Program ID String(10)
,''			SZJOBN -- Work Station ID String(10)
,''			SZUPMJ -- Date - Updated Date(6)
,''			SZTDAY -- Time of Day Numeric(6)
,''			SZUPMT -- Time - Last Updated Numeric(6)
,''			SZPRGF -- Purge Flag Character(1)
,''			SZSCCLTP -- Shortcut Client Type (future) String(2)
,''			SZPA8 -- Address Number - Parent Numeric(8)
,''			SZTICKER -- Ticker String(10)
,''			SZEXCHG -- Stock Exchange String(10)
,''			SZDUNS -- DUNS Number String(13)
,''			SZCLASS01 -- Classification Code 01 String(3)
,''			SZCLASS02 -- Classification Code 02 String(3)
,''			SZCLASS03 -- Classification Code 03 String(3)
,''			SZCLASS04 -- Classification Code 04 String(3)
,''			SZCLASS05 -- Classification Code 05 String(3)
,''			SZNOE -- Number Of Employee Numeric(15)
,''			SZGROWTHR -- Growth Rate Numeric(8)
,''			SZYEARSTAR -- Year Started String(15)
,''			SZAEMPGP -- Employee Group Approvals String(5)
,''			SZACTIN -- Future Use Indicator Character(1)
,''			SZREVRNG -- Revenue range String(5)
