use BALCO;

SELECT     PB.PART_ID, CONVERT(varchar(8000)
		, CONVERT(binary(8000), PB.BITS)) AS "Item Specifications"
FROM         PART_BINARY PB

JOIN _ITEM_MASTER_SIDE IMS
ON LEFT(IMS.SZAITM,25) = LEFT(PB.PART_ID,25)

JOIN PART PART
	ON LEFT(IMS.SZAITM,25) = LEFT(PART.ID,25)

WHERE PART.ABC_CODE <> 'Z'