
-- CREATE VIEW _BT_ST AS

	SELECT -- BillTo addresses
		 BT.SZAN8
		,BT.SZALKY
		,'BT' AS TYPE
		,BT.SZAT1
		,REPLACE(BT.SZALKY ,'BC_','') BILLTO_REF
		,BT.SZAN8 BILLTO_ID
		,0 ADDR_NO
	FROM dbo._BILLTO BT
	
	UNION ALL

	SELECT -- ShipTo addresses
		 ST.SZAN8
		,ST.SZALKY
		,'ST' AS TYPE
		,'CS' SZAT1
		,SUBSTRING (REPLACE(ST.SZALKY ,'BC_',''),0,CHARINDEX('_',REPLACE(ST.SZALKY ,'BC_',''))) BILLTO_REF
		,BT2.SZAN8 BILLTO_ID
		,SUBSTRING(REPLACE(ST.SZALKY ,'BC_',''),CHARINDEX('_',REPLACE(ST.SZALKY ,'BC_',''))+1,LEN(REPLACE(ST.SZALKY ,'BC_',''))) ADDR_NO
	FROM _SHIPTO ST
	
	JOIN _BILLTO BT2
	ON 'BC_' + SUBSTRING (REPLACE(ST.SZALKY ,'BC_',''),0,CHARINDEX('_',REPLACE(ST.SZALKY ,'BC_',''))) = BT2.SZALKY
	
