

 ''   LMMCU --Business Unit String(12)
,''   LMLOCN --Location String(20)
,''   LMAISL --Aisle String(8)
,''   LMBIN --Bin String(8)
,''   LMLA03 --Category Code - Location 03 String(4)
,''   LMLA04 --Category Code - Location 04 String(4)
,''   LMLA05 --Category Code - Location 05 String(4)
,''   LMLA06 --Category Code - Location 06 String(4)
,''   LMLA07 --Category Code - Location 07 String(4)
,''   LMLA08 --Category Code - Location 08 String(4)
,''   LMLA09 --Category Code - Location 09 String(4)
,''   LMLA10 --Category Code - Location 10 String(4)
,''   LMLLDL --Level of Detail - Location Character(1)
,''   LMSTY1 --Group - Location Dimension String(6)
,''   LMCGRP --Group - Location Characteristics String(6)
,''   LMLHLD --Hold Code - Location String(2)
,''   LMFREZ --Freeze Rule Character(1)
,''   LMNETA --Nettable Allocatable Code Character(1)
,''   LMMNUP --Percentage - Minimum Putaway Numeric(5)
,''   LMMNUK --Percentage - Minimum Pick Numeric(5)
,''   LMLCOD --Code - Location Tax Status String(2)
,''   LMMMTH --Move Method Code String(4)
,''   LMEQTY --Container Code String(5)
,''   LMCTNF --Carton Recommendation (Y/N) Character(1)
,''   LMMCNT --Mix Containers (Y/N) Character(1)
,''   LMMLOT --Mix Dates / Lots (Y/N) Character(1)
,''   LMMITM --Maximum Number of Items Numeric(2)
,''   LMSTAG --Staging Location (Y/N) Character(1)
,''   LMLVER --Code - Location Verification String(5)
,''   LMPCNF --Storage Confirmation Required (Y/N) Character(1)
,''   LMKCNF --Retrieval Confirmation Required (Y/N) Character(1)
,''   LMAPUT --Allow Putaway (Y/N) Character(1)
,''   LMAPIK --Allow Pick (Y/N) Character(1)
,''   LMARPL --Allow Replenishment (Y/N) Character(1)
,''   LMPZON --Zone - Putaway String(6)
,''   LMKZON --Zone - Picking String(6)
,''   LMZONR --Zone - Replenishment String(6)
,''   LMSTGP --Staging Location - Putaway String(20)
,''   LMSTGK --Staging Location - Picking String(20)
,''   LMSTGR --Staging Location - Replenishment String(20)
,''   LMWSQP --Sequence Code - Putaway Numeric(5)
,''   LMWSQQ --Sequence Code - Picking Numeric(5)
,''   LMWSQR --Sequence Code - Replenishment Numeric(5)
,''   LMDISX --Latitude Numeric(5)
,''   LMDISY --Longitude Numeric(5)
,''   LMDISZ --Height Numeric(5)
,''   LMEQTP --Equipment Type String(3)
,''   LMURCD --User Reserved Code String(2)
,''   LMURDT --User Reserved Date Date(6)
,''   LMURAT --User Reserved Amount Numeric(15)
,''   LMURAB --User Reserved Number Numeric(8)
,''   LMURRF --User Reserved Reference String(15)
,''   LMOT1Y --Potency Control Character(1)
,''   LMOT2Y --Grade Control Character(1)
,''   LMUSER --User ID String(10)
,''   LMPID --Program ID String(10)
,''   LMJOBN --Work Station ID String(10)
,''   LMUPMJ --Date - Updated Date(6)
,''   LMTDAY --Time of Day Numeric(6)
,''   LMMIXL --Mix Item/Lot Character(1)
,''   LMMPTL --Merge Partials Character(1)
,''   LMMUMS --Merge Unit of Measure Structures Character(1)
