SELECT SYSCOLUMNS.TABLE_SCHEMA
	,SYSCOLUMNS.TABLE_NAME
	,SYSCOLUMNS.COLUMN_NAME
	,SYSCOLUMNS.COLUMN_TEXT
	,SYSCOLUMNS.DATA_TYPE
	,SYSCOLUMNS.LENGTH
	,SYSCOLUMNS.NUMERIC_SCALE
	,SYSCOLUMNS.NUMERIC_PRECISION
	,SYSCOLUMNS.IS_NULLABLE
FROM QSYS2.SYSCOLUMNS SYSCOLUMNS
WHERE (SYSCOLUMNS.TABLE_SCHEMA = ?)
	AND (SYSCOLUMNS.TABLE_NAME = ?)