/*
    F4100 - Location Master
    VER0001 -  Tom Sampson
*/

SELECT

 '' LMMCU -- Business Unit [Generic Edit] String (12)
,'' LMLOCN -- Location [Generic Edit] String (20)
,'' LMAISL -- Aisle [Generic Edit] String (8)
,'' LMBIN -- Bin [Generic Edit] String (8)
,'' LMLA03 -- Category Code - Location 03 [Generic Edit] String (4)
,'' LMLA04 -- Category Code - Location 04 [Generic Edit] String (4)
,'' LMLA05 -- Category Code - Location 05 [Generic Edit] String (4)
,'' LMLA06 -- Category Code - Location 06 [Generic Edit] String (4)
,'' LMLA07 -- Category Code - Location 07 [Generic Edit] String (4)
,'' LMLA08 -- Category Code - Location 08 [Generic Edit] String (4)
,'' LMLA09 -- Category Code - Location 09 [Generic Edit] String (4)
,'' LMLA10 -- Category Code - Location 10 [Generic Edit] String (4)
,'' LMLLDL -- Level of Detail - Location [UDC (H40 LL)] Character (1)
,'' LMSTY1 -- Group - Location Dimension [UDC (46 LD)] String (6)
,'' LMCGRP -- Group - Location Characteristics [UDC (46 LC)] String (6)
,'' LMLHLD -- Hold Code - Location [Generic Edit] String (2)
,'' LMFREZ -- Freeze Rule [UDC (H46 FR)] Character (1)
,'' LMNETA -- Nettable Allocatable Code [Generic Edit] Character (1)
,'' LMMNUP -- Percentage - Minimum Putaway [Generic Edit] Numeric (5)
,'' LMMNUK -- Percentage - Minimum Pick [Generic Edit] Numeric (5)
,'' LMLCOD -- Code - Location Tax Status [UDC (46 LT)] String (2)
,'' LMMMTH -- Move Method Code [Generic Edit] String (4)
,'' LMEQTY -- Container Code [UDC (46 EQ)] String (5)
,'' LMCTNF -- Carton Recommendation (Y/N) [Generic Edit] Character (1)
,'' LMMCNT -- Mix Containers (Y/N) [Generic Edit] Character (1)
,'' LMMLOT -- Mix Dates / Lots (Y/N) [Generic Edit] Character (1)
,'' LMMITM -- Maximum Number of Items [Generic Edit] Numeric (2)
,'' LMSTAG -- Staging Location (Y/N) [Generic Edit] Character (1)
,'' LMLVER -- Code - Location Verification [Generic Edit] String (5)
,'' LMPCNF -- Storage Confirmation Required (Y/N) [Generic Edit] Character (1)
,'' LMKCNF -- Retrieval Confirmation Required (Y/N) [Generic Edit] Character (1)
,'' LMAPUT -- Allow Putaway (Y/N) [Generic Edit] Character (1)
,'' LMAPIK -- Allow Pick (Y/N) [Generic Edit] Character (1)
,'' LMARPL -- Allow Replenishment (Y/N) [Generic Edit] Character (1)
,'' LMPZON -- Zone - Putaway [UDC (46 ZN)] String (6)
,'' LMKZON -- Zone - Picking [UDC (46 ZN)] String (6)
,'' LMZONR -- Zone - Replenishment [UDC (46 ZN)] String (6)
,'' LMSTGP -- Staging Location - Putaway [Generic Edit] String (20)
,'' LMSTGK -- Staging Location - Picking [Generic Edit] String (20)
,'' LMSTGR -- Staging Location - Replenishment [Generic Edit] String (20)
,'' LMWSQP -- Sequence Code - Putaway [Generic Edit] Numeric (5)
,'' LMWSQQ -- Sequence Code - Picking [Generic Edit] Numeric (5)
,'' LMWSQR -- Sequence Code - Replenishment [Generic Edit] Numeric (5)
,'' LMDISX -- Latitude [Generic Edit] Numeric (5)
,'' LMDISY -- Longitude [Generic Edit] Numeric (5)
,'' LMDISZ -- Height [Generic Edit] Numeric (5)
,'' LMEQTP -- Equipment Type [Generic Edit] String (3)
,'' LMURCD -- User Reserved Code [Generic Edit] String (2)
,'' LMURDT -- User Reserved Date [Generic Edit] Date (6)
,'' LMURAT -- User Reserved Amount [Generic Edit] Numeric (15)
,'' LMURAB -- User Reserved Number [Generic Edit] Numeric (8)
,'' LMURRF -- User Reserved Reference [Generic Edit] String (15)
,'' LMOT1Y -- Potency Control [Generic Edit] Character (1)
,'' LMOT2Y -- Grade Control [Generic Edit] Character (1)
,'' LMUSER -- User ID [Generic Edit] String (10)
,'' LMPID -- Program ID [Generic Edit] String (10)
,'' LMJOBN -- Work Station ID [Generic Edit] String (10)
,'' LMUPMJ -- Date - Updated [Generic Edit] Date (6)
,'' LMTDAY -- Time of Day [Generic Edit] Numeric (6)
,'' LMMIXL -- Mix Item/Lot [UDC (41 ML)] Character (1)
,'' LMMPTL -- Merge Partials [Generic Edit] Character (1)
,'' LMMUMS -- Merge Unit of Measure Structures [Generic Edit] Character (1)

FROM

TBD