     ,CASE
		WHEN REPLACE(LEFT(REPLACE(SZALKY,'BC_',''),CHARINDEX('_', REPLACE(SZALKY,'BC_',''))),'_','') = ''
			THEN REPLACE(SZALKY,'BC_','')
			ELSE REPLACE(LEFT(REPLACE(SZALKY,'BC_',''),CHARINDEX('_', REPLACE(SZALKY,'BC_',''))),'_','')
	  END