SELECT DISTINCT

	 CUSTOMER_ORDER.ID
	,CASE
		WHEN WORK_ORDER.ACT_MATERIAL_COST = 0
			OR WORK_ORDER.DESIRED_QTY = 0 
		THEN 0
		ELSE ((WORK_ORDER.ACT_MATERIAL_COST/WORK_ORDER.DESIRED_QTY) * 1.7)
	 END CALCULATED_COST_PER_UNIT

FROM   DEMAND_SUPPLY_LINK DEMAND_SUPPLY_LINK

JOIN WORK_ORDER WORK_ORDER 
	ON DEMAND_SUPPLY_LINK.SUPPLY_BASE_ID = WORK_ORDER.BASE_ID 
	AND DEMAND_SUPPLY_LINK.SUPPLY_LOT_ID = WORK_ORDER.LOT_ID 
	AND DEMAND_SUPPLY_LINK.SUPPLY_SPLIT_ID = WORK_ORDER.SPLIT_ID 
	AND DEMAND_SUPPLY_LINK.SUPPLY_SUB_ID = WORK_ORDER.SUB_ID 


JOIN CUSTOMER_ORDER CUSTOMER_ORDER
	ON DEMAND_SUPPLY_LINK.DEMAND_BASE_ID = CUSTOMER_ORDER.ID

JOIN CUST_ORDER_LINE CUST_ORDER_LINE
	ON CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID
	AND CUST_ORDER_LINE.LINE_NO = DEMAND_SUPPLY_LINK.DEMAND_SEQ_NO

/*
LEFT JOIN _ADDRESS_BOOK_TABLE ADDRESS_BOOK
    ON CAST(ORDER_REF.SHIPTO_ID AS BIGINT) = CAST(ADDRESS_BOOK.SZAN8 AS BIGINT)	
*/

JOIN RECEIVABLE_LINE RECEIVABLE_LINE
    ON RECEIVABLE_LINE.CUST_ORDER_ID = CUST_ORDER_LINE.CUST_ORDER_ID
    AND RECEIVABLE_LINE.CUST_ORDER_LINE_NO = CUST_ORDER_LINE.LINE_NO

JOIN RECEIVABLE RECEIVABLE
    ON RECEIVABLE.INVOICE_ID = RECEIVABLE_LINE.INVOICE_ID
    
JOIN PART PART
    ON PART.ID = CUST_ORDER_LINE.PART_ID    

WHERE  CUSTOMER_ORDER.ORDER_DATE >= '2017/10/1'

ORDER BY CUSTOMER_ORDER.ID