SELECT 
	 SZAN8
	,SZALKY
	,CASE 
		WHEN SUBSTRING(RIGHT(SZALKY,LEN(SZALKY)-3), CHARINDEX('_', RIGHT(SZALKY,LEN(SZALKY)-3)) + 1, LEN(RIGHT(SZALKY,LEN(SZALKY)-3))) = RIGHT(SZALKY,LEN(SZALKY)-3) THEN RIGHT(SZALKY,LEN(SZALKY)-3)
		ELSE LEFT(RIGHT(SZALKY,LEN(SZALKY)-3),LEN(RIGHT(SZALKY,LEN(SZALKY)-3)) - LEN(SUBSTRING(RIGHT(SZALKY,LEN(SZALKY)-3), CHARINDEX('_', RIGHT(SZALKY,LEN(SZALKY)-3)), LEN(RIGHT(SZALKY,LEN(SZALKY)-3)))))
	 END BILLTO_ID

	,CASE 
		WHEN SUBSTRING(RIGHT(SZALKY,LEN(SZALKY)-3), CHARINDEX('_', RIGHT(SZALKY,LEN(SZALKY)-3)) + 1, LEN(RIGHT(SZALKY,LEN(SZALKY)-3))) = RIGHT(SZALKY,LEN(SZALKY)-3) THEN 0
		ELSE SUBSTRING(RIGHT(SZALKY,LEN(SZALKY)-3), CHARINDEX('_', RIGHT(SZALKY,LEN(SZALKY)-3)) + 1, LEN(RIGHT(SZALKY,LEN(SZALKY)-3)))
	 END ADDR_NO	 

	
FROM _ADDRESS_BOOK

ORDER BY SZAN8