-- This was the query used for a long time to create a customer mailing list.  It is flawed because it based on shipping adresses rather than remit-to/bill-to addresses.

SELECT

	 -- MBFBREP.FBAENB	-- COMPANY NUMBER
	 MBFBREP.FBCANB	CUS_NUM -- CUSTOMER NUMBER
	,100000 + CAST(SUBSTR(TRIM(MBFBREP.FBCANB), 1, LENGTH(TRIM(MBFBREP.FBCANB)) - 2) AS INTEGER) JDE_ID
	,CUSCRSRF.GRPNO	-- GROUP# QS36F
	,CASE
		WHEN CUSCRSRF.GRPNO <> 0 THEN SUBSTR(CUSCRSRF.GRPNO ,2,5)
		ELSE ''
	 END MAIN_GROUP	
	,CASE
		WHEN CUSCRSRF.GRPNO <> 0 THEN SUBSTR(CUSCRSRF.GRPNO ,1,1)
		ELSE ''
	 END SUB_GROUP	
	,CUSMAS.CUSNM -- CUSTOMER NAME

	,RTRIM(MBALREP.ALCLTX) ADDRLINE1
	,RTRIM(MBALREP.ALCMTX) ADDRLINE2
	,RTRIM(MBALREP.ALCNTX) ADDRLINE3

--	,RTRIM(MBALREP.ALCOTX) ADDRLINE4
--	,RTRIM(MBALREP.ALZ9HH) ADDRLINE5
--	,RTRIM(MBALREP.ALZ9HG) ADDRLINE6

	,MBALREP.ALCQTX CONTACTNAME
	,MBALREP.ALCRTX PHONENUM
	,MBALREP.ALCOCD COUNTRYCODE

    ,COUNTRY_REF.A2

	,RTRIM(MBALREP.ALBYCD) STATE
	,RTRIM(MBALREP.ALCPTX) CITY
	,RTRIM(MBALREP.ALCVCD) POSTALCODE    

	,MBALREP.ALE2ST ADDRTYPE
	,MBALREP.ALCUCD ADDRCODE
	,MBBFREP.BFHYST ADDRFORMAT

	,COUNT(*) ORDER_COUNT
	,DATE(CONCAT(
		CONCAT(
			CONCAT(
				SUBSTR(CHAR(( MIN(MBFBREP.FBACDT) - 1000000 ) + 20000000), 1, 4), '-'), 
   			CONCAT(
   				SUBSTR(CHAR(( MIN(MBFBREP.FBACDT) - 1000000 ) + 20000000), 5, 2),'-')),
   				SUBSTR(CHAR(( MIN(MBFBREP.FBACDT) - 1000000 ) + 20000000), 7, 2))) OLDEST_ORDER	 -- OLDEST	QUOTE/ORDER DATE
	,DATE(CONCAT(
		CONCAT(
			CONCAT(
				SUBSTR(CHAR(( MAX(MBFBREP.FBACDT) - 1000000 ) + 20000000), 1, 4), '-'), 
   			CONCAT(
   				SUBSTR(CHAR(( MAX(MBFBREP.FBACDT) - 1000000 ) + 20000000), 5, 2),'-')),
   				SUBSTR(CHAR(( MAX(MBFBREP.FBACDT) - 1000000 ) + 20000000), 7, 2))) NEWEST_ORDER	 -- MOST RECENT	QUOTE/ORDER DATE	



	,IFNULL(GRPWSG.GRPNM,'') GROUP_NAME
	,CUSCRSRF.ENTGRP	-- ENTITY GROUP MAPICS
	,CUSCRSRF.MKT	-- MARKET QS36F
	,CUSCRSRF.TERR	-- TERRITORY QS36F
	,CUSCRSRF.SLSREP	-- SALES REP MAPICS
	,CUSCRSRF.CUSCLS	-- CUST. CLASS MAPICS
	-- ,CUSCRSRF.MKTANL	-- MARKET ANALYS MAPICS
	-- ,CUSCRSRF.TERTRY	-- TERRITORY MAPICS
	-- ,CUSCRSRF.MKTERR	-- MKTERR QS36F
	,CUSCRSRF.BYGRCD	-- BUYING GROUP CODE
	,CUSCRSRF.BYGRDS	-- GROUP DESCRIPTION

FROM AMFLIB.MBFBREP MBFBREP -- SHIP HIST

JOIN AMFLIB.MBBFREP MBBFREP -- Customer physical file
     ON MBFBREP.FBAENB = MBBFREP.COMNO	-- Company number
    AND MBFBREP.FBCANB = MBBFREP.CUSNO	-- Customer number

JOIN AMFLIB.MBDEREP MBDEREP -- Ship To
     ON	MBBFREP.COMNO = MBDEREP.DEAENB -- Company Number
    AND MBBFREP.CUSNO = MBDEREP.DECANB -- Customer Number

JOIN AMFLIB.MBALREP MBALREP -- address table
     ON MBDEREP.DEAENB = MBALREP.ALAENB -- Company Number
    AND MBDEREP.DECANB = MBALREP.ALCANB -- Customer Number
    AND MBDEREP.DEE2ST = MBALREP.ALE2ST -- Address type
    AND MBDEREP.DECUCD = MBALREP.ALCUCD -- Address Code

JOIN AMFLIB.CUSMAS CUSMAS -- CUSTOMER MASTER
     ON MBFBREP.FBAENB = CUSMAS.COMNO -- Company number
    AND MBFBREP.FBCANB = CUSMAS.CUSNO -- Customer number

JOIN RSF.CUSCRSRF CUSCRSRF -- CUSTOMER CROSS REF
	 ON CUSMAS.CUSNO = CUSCRSRF.CUSNO8

JOIN QS36F.GRPWSG GRPWSG -- CUSTOMER GROUPS
	 ON CUSCRSRF.SGROUP = GRPWSG.GROUP

LEFT JOIN TOMQRY.COUNTRY_REF COUNTRY_REF
     ON MBALREP.ALCOCD = COUNTRY_REF.A3

WHERE RIGHT(FBCANB,2) = '01' -- all customer numbers end in 01
-- AND CUSCRSRF.GRPNO = 0
-- AND LEFT(CUSMAS.CUSNM,1) = 'A'
AND MBFBREP.FBACDT >= 1161001

GROUP BY 

	 MBFBREP.FBAENB	-- COMPANY NUMBER
	,MBFBREP.FBCANB	-- CUSTOMER NUMBER
	,CUSMAS.CUSNM -- CUSTOMER NAME

	,MBALREP.ALE2ST -- ADDRTYPE
	,MBALREP.ALCUCD -- ADDRCODE
	,MBBFREP.BFHYST -- ADDRFORMAT
	,RTRIM(MBALREP.ALCLTX) -- ADDRNAME
	,RTRIM(MBALREP.ALCMTX) -- ADDRLINE1
	,RTRIM(MBALREP.ALCNTX) -- ADDRLINE2
	,RTRIM(MBALREP.ALCOTX) -- ADDRLINE3
	,RTRIM(MBALREP.ALZ9HH) -- ADDRLINE4
	,RTRIM(MBALREP.ALZ9HG) -- ADDRLINE5
	,MBALREP.ALCQTX -- CONTACTNAME
	,MBALREP.ALCRTX -- PHONENUM
	,MBALREP.ALCOCD -- COUNTRYCODE
    ,COUNTRY_REF.A2 -- A2 country code for JDE
	,RTRIM(MBALREP.ALBYCD) -- STATE
	,RTRIM(MBALREP.ALCPTX) -- CITY
	,RTRIM(MBALREP.ALCVCD) -- POSTALCODE  

	,GRPWSG.GRPNM -- GROUP NAME
	,CUSCRSRF.GRPNO -- CROSS REF CUSNOL FOR CUSMASL

	,CUSCRSRF.GRPNO	-- GROUP# QS36F
	,CUSCRSRF.ENTGRP	-- ENTITY GROUP MAPICS
	,CUSCRSRF.MKT	-- MARKET QS36F
	,CUSCRSRF.TERR	-- TERRITORY QS36F
	,CUSCRSRF.SLSREP	-- SALES REP MAPICS
	,CUSCRSRF.CUSCLS	-- CUST. CLASS MAPICS
	-- ,CUSCRSRF.MKTANL	-- MARKET ANALYS MAPICS
	-- ,CUSCRSRF.TERTRY	-- TERRITORY MAPICS
	-- ,CUSCRSRF.MKTERR	-- MKTERR QS36F
	,CUSCRSRF.BYGRCD	-- BUYING GROUP CODE
	,CUSCRSRF.BYGRDS	-- GROUP DESCRIPTION

	
ORDER BY

	 CUSCRSRF.GRPNO	
	,CUSMAS.CUSNM