SELECT DISTINCT

	 MBBWCPP.BWCANB "CUST_NO" -- Customer number
	,MBBWCPP.BWAQTX --Customer name
	,CASE 
		WHEN CUSCRSRF.GRPNO <> 0
			THEN SUBSTR(CUSCRSRF.GRPNO, 2, 5)
		ELSE ''
		END MAIN_GROUP
	,CASE 
		WHEN CUSCRSRF.GRPNO <> 0
			THEN SUBSTR(CUSCRSRF.GRPNO, 1, 1)
		ELSE ''
		END SUB_GROUP
	,MBBWCPP.BWCANB "CUST_BAR" -- Customer number
	,RTRIM(MBALREP.ALCMTX) ADDRLINE2
	,RTRIM(CUO."Addr2_Update") ADDR2_UPDATE
	,RTRIM(MBALREP.ALCPTX) CITY
	,RTRIM(CUO."City_Update") CITY_UPDATE
	,RTRIM(MBALREP.ALBYCD) STATE
	,RTRIM(CUO."State_Update") STATE_UPDATE

FROM AMFLIB.MBBWCPP MBBWCPP -- Historical customer order
JOIN AMFLIB.MBF9REP MBF9REP -- Invoice header
	ON MBBWCPP.BWGGNB = MBF9REP.FEGGNB -- invoice number
JOIN AMFLIB.MBALREP MBALREP -- address table
	ON MBBWCPP.BWAENB = MBALREP.ALAENB -- Company Number
		AND MBBWCPP.BWCANB = MBALREP.ALCANB -- Customer Number
LEFT JOIN TOMQRY.COUNTRY_REF COUNTRY_REF -- country code a3 to a2 conversion
	ON MBALREP.ALCOCD = COUNTRY_REF.A3
JOIN AMFLIB.CUSMAS CUSMAS -- CUSTOMER MASTER
	ON MBBWCPP.BWAENB = CUSMAS.COMNO -- Company number
		AND MBBWCPP.BWCANB = CUSMAS.CUSNO -- Customer number
LEFT JOIN RSF.CUSCRSRF CUSCRSRF -- CUSTOMER CROSS REF
	ON CUSMAS.CUSNO = CUSCRSRF.CUSNO8
LEFT JOIN QS36F.GRPWSG GRPWSG -- CUSTOMER GROUPS
	ON CUSCRSRF.SGROUP = GRPWSG.
GROUP
JOIN TOMQRY.CLEAN_UP_ONE CUO
	ON RTRIM(MBALREP.ALCMTX) = RTRIM(CUO."Addr2")
		AND RTRIM(MBALREP.ALBYCD) = RTRIM(MBALREP.ALBYCD)
		AND RTRIM(MBALREP.ALCPTX) = RTRIM(CUO."City")
WHERE MBF9REP.FEGHNB > 1160101
	AND MBALREP.ALE2ST = 1 -- Address type
	AND MBALREP.ALCUCD = 1 -- Address code
	AND MBF9REP.FEIZVA > 0 --	Total invoice amount
	AND CUO."Dupe" = 1
	AND (
		CUO."Addr2_Update" IS NOT NULL
		OR CUO."City_Update" IS NOT NULL
		OR CUO."State_Update" IS NOT NULL
		)
ORDER BY RTRIM(MBALREP.ALCPTX)
	,RTRIM(MBALREP.ALBYCD)
	,RTRIM(MBALREP.ALCMTX) -- ADDRLINE2