/*
    F4101Z1 - Item Master
    VER0001 -  Tom Sampson
*/

SELECT

 '' SZEDUS -- EDI - User ID [Generic Edit] String (10)
,'' SZEDBT -- EDI - Batch Number [Generic Edit] String (15)
,'' SZEDTN -- EDI - Transaction Number [Generic Edit] String (22)
,'' SZEDLN -- EDI - Line Number [Generic Edit] Numeric (7)
,'' SZEDCT -- EDI - Document Type [Generic Edit] String (2)
,'' SZTYTN -- Type - Transaction [UDC (00 TT)] String (8)
,'' SZEDFT -- EDI - Translation Format [Generic Edit] String (10)
,'' SZEDDT -- EDI - Transmission Date [Generic Edit] Date (6)
,'' SZDRIN -- Direction Indicator [UDC (00 DN)] Character (1)
,'' SZEDDL -- EDI - Detail Lines Processed [Generic Edit] Numeric (5)
,'' SZEDSP -- EDI - Successfully Processed [Generic Edit] Character (1)
,'' SZPNID -- Trading Partner ID [Generic Edit] String (15)
,'' SZTNAC -- Transaction Action [UDC (00 TA)] String (2)
,'' SZITBR -- Update Item Branch [Generic Edit] Character (1)
,'' SZITM -- Item Number - Short [Generic Edit] Numeric (8)
,'' SZKIT -- Parent (short) Item Number [Generic Edit] Numeric (8)
,'' SZLITM -- 2nd Item Number [Generic Edit] String (25)
,'' SZAITM -- 3rd Item Number [Generic Edit] String (25)
,'' SZDSC1 -- Description [Generic Edit] String (30)
,'' SZDSC2 -- Description - Line 2 [Generic Edit] String (30)
,'' SZSRTX -- Search Text [Generic Edit] String (30)
,'' SZALN -- Search Text - Compressed [Generic Edit] String (30)
,'' SZSRP1 -- Sales Catalog Section [UDC (41 S1)] String (3)
,'' SZSRP2 -- Sub Section [UDC (41 S2)] String (3)
,'' SZSRP3 -- Sales Category Code 3 [UDC (41 S3)] String (3)
,'' SZSRP4 -- Sales Category Code 4 [UDC (41 S4)] String (3)
,'' SZSRP5 -- Sales Category Code 5 [UDC (41 S5)] String (3)
,'' SZSRP6 -- Category Code 6 [UDC (41 06)] String (6)
,'' SZSRP7 -- Category Code 7 [UDC (41 07)] String (6)
,'' SZSRP8 -- Category Code 8 [UDC (41 08)] String (6)
,'' SZSRP9 -- Category Code 9 [UDC (41 09)] String (6)
,'' SZSRP0 -- Category Code 10 [UDC (41 10)] String (6)
,'' SZPRP1 -- Commodity Class [UDC (41 P1)] String (3)
,'' SZPRP2 -- Commodity Sub Class [UDC (41 P2)] String (3)
,'' SZPRP3 -- Supplier Rebate Code [UDC (41 P3)] String (3)
,'' SZPRP4 -- Master Planning Family [UDC (41 P4)] String (3)
,'' SZPRP5 -- Purchasing Category Code 5 [UDC (41 P5)] String (3)
,'' SZPRP6 -- Group - Item Dimension [UDC (41 01)] String (6)
,'' SZPRP7 -- Group - Warehouse Process 1 [UDC (41 02)] String (6)
,'' SZPRP8 -- Group - Warehouse Process 2 [UDC (41 02)] String (6)
,'' SZPRP9 -- Group - Warehouse Process 3 [UDC (41 02)] String (6)
,'' SZPRP0 -- Item Pool [UDC (41 05)] String (6)
,'' SZCDCD -- Commodity Code [Generic Edit] String (15)
,'' SZPDGR -- Product Group [UDC (41B PG)] String (3)
,'' SZDSGP -- Dispatch Group [UDC (41B DG)] String (3)
,'' SZPRGR -- Item Price Group [UDC (40 PI)] String (8)
,'' SZRPRC -- Reprice (Basket Price) Category [UDC (40 PI)] String (8)
,'' SZORPR -- Order Reprice Category [UDC (40 PI)] String (8)
,'' SZBUYR -- Buyer Number [Generic Edit] Numeric (8)
,'' SZDRAW -- Drawing Number [Generic Edit] String (20)
,'' SZRVNO -- Last Revision No. [Generic Edit] String (2)
,'' SZDSZE -- Drawing Size [Generic Edit] Character (1)
,'' SZVCUD -- Cubic Dimensions - Volume [Generic Edit] Numeric (15)
,'' SZCARS -- Carrier Number [Generic Edit] Numeric (8)
,'' SZCARP -- Preferred Carrier - Purchasing [Generic Edit] Numeric (8)
,'' SZSHCN -- Shipping Conditions Code [UDC (41 C)] String (3)
,'' SZSHCM -- Shipping Commodity Class [UDC (41 E)] String (3)
,'' SZUOM1 -- Unit of Measure - Primary [UDC (00 UM)] String (2)
,'' SZUOM2 -- Unit of Measure - Secondary [UDC (00 UM)] String (2)
,'' SZUOM3 -- Unit of Measure - Purchasing [UDC (00 UM)] String (2)
,'' SZUOM4 -- Unit of Measure - Pricing [UDC (00 UM)] String (2)
,'' SZUOM6 -- Unit of Measure - Shipping [UDC (00 UM)] String (2)
,'' SZUOM8 -- Unit of Measure - Production [UDC (00 UM)] String (2)
,'' SZUOM9 -- Unit of Measure - Component [UDC (00 UM)] String (2)
,'' SZUWUM -- Unit of Measure - Weight [UDC (00 UM)] String (2)
,'' SZUVM1 -- Unit of Measure - Volume [UDC (00 UM)] String (2)
,'' SZSUTM -- Unit of Measure - Stocking [UDC (00 UM)] String (2)
,'' SZUMVW -- Unit of Measure - Volume or Weight [UDC (39 VW)] Character (1)
,'' SZCYCL -- Cycle Count Category [UDC (41 8)] String (3)
,'' SZGLPT -- Category - G/L [UDC (41 9)] String (4)
,'' SZPLEV -- Level - Sales Base Price [UDC (H40 PL)] Character (1)
,'' SZPPLV -- Level - Purchase Price [UDC (H40 PP)] Character (1)
,'' SZCLEV -- Level - Inventory Cost [UDC (H40 CL)] Character (1)
,'' SZPRPO -- Grade/Potency Pricing [UDC (40 LP)] Character (1)
,'' SZCKAV -- Check Availability Y/N [Generic Edit] Character (1)
,'' SZBPFG -- Bulk/Packed Flag [UDC (41B BF)] Character (1)
,'' SZSRCE -- Layer Code - Source [UDC (H41 SR)] Character (1)
,'' SZOT1Y -- Potency Control [Generic Edit] Character (1)
,'' SZOT2Y -- Grade Control [Generic Edit] Character (1)
,'' SZSTDP -- Standard Potency [Generic Edit] Numeric (7)
,'' SZFRMP -- From Potency [Generic Edit] Numeric (7)
,'' SZTHRP -- Thru Potency [Generic Edit] Numeric (7)
,'' SZSTDG -- Standard Grade [UDC (40 LG)] String (3)
,'' SZFRGD -- From Grade [UDC (40 LG)] String (3)
,'' SZTHGD -- Thru Grade [UDC (40 LG)] String (3)
,'' SZCOTY -- Component Type [UDC (H40 CP)] Character (1)
,'' SZSTKT -- Stocking Type [UDC (41 I)] Character (1)
,'' SZLNTY -- Line Type [Generic Edit] String (2)
,'' SZCONT -- Contract - Item [Generic Edit] Character (1)
,'' SZBACK -- Backorders Allowed (Y/N) [Generic Edit] Character (1)
,'' SZIFLA -- Item Flash Message [UDC (40 FL)] String (2)
,'' SZTFLA -- Standard Unit of Measure Conversion [UDC (H40 ST)] String (2)
,'' SZINMG -- Print Message [UDC (40 PM)] String (10)
,'' SZABCS -- ABC Code 1 - Sales - Inventory [UDC (H41 AB)] Character (1)
,'' SZABCM -- ABC Code 1 - Margin - Inventory [UDC (H41 AB)] Character (1)
,'' SZABCI -- ABC Code 3 - Investment - Inventory [UDC (H41 AB)] Character (1)
,'' SZOVR -- ABC Code Override Indicator [Generic Edit] Character (1)
,'' SZWARR -- Type Warranty [Generic Edit] String (8)
,'' SZCMCG -- Commission Category [Generic Edit] String (8)
,'' SZSRNR -- Serial Number Required [UDC (H41 NR)] Character (1)
,'' SZPMTH -- Method - Kit/Configurator Pricing [UDC (H41 PM)] Character (1)
,'' SZFIFO -- FIFO Processing [Generic Edit] Character (1)
,'' SZLOTS -- Lot Status Code [UDC (41 L)] Character (1)
,'' SZSLD -- Days - Shelf Life Days [Generic Edit] Numeric (6)
,'' SZANPL -- Planner Number [Generic Edit] Numeric (8)
,'' SZMPST -- Planning Code [UDC (H41 MP)] Character (1)
,'' SZPCTM -- Percent Margin [Generic Edit] Numeric (7)
,'' SZMMPC -- Margin Maintenance (%) [Generic Edit] Numeric (7)
,'' SZPTSC -- Material Status [UDC (40 PS)] String (2)
,'' SZSNS -- Round to Whole Number [UDC (H41 SN)] Character (1)
,'' SZLTLV -- Leadtime Level [Generic Edit] Numeric (5)
,'' SZLTMF -- Leadtime MFG [Generic Edit] Numeric (5)
,'' SZLTCM -- Leadtime Cumulative [Generic Edit] Numeric (5)
,'' SZOPC -- Order Policy Code [UDC (H41 OP)] Character (1)
,'' SZOPV -- Value - Order Policy [Generic Edit] Numeric (15)
,'' SZACQ -- Quantity - Accounting Cost [Generic Edit] Numeric (15)
,'' SZMLQ -- Quantity - MFG Leadtime [Generic Edit] Numeric (15)
,'' SZLTPU -- Leadtime Per Unit [Generic Edit] Numeric (5)
,'' SZMPSP -- Planning Time Fence Rule [UDC (34 TF)] Character (1)
,'' SZMRPP -- Fixed or Variable Leadtime [UDC (H41 MS)] Character (1)
,'' SZITC -- Issue Type Code [UDC (41 IT)] Character (1)
,'' SZORDW -- Order With [Generic Edit] Character (1)
,'' SZMTF1 -- Planning Time Fence Days [Generic Edit] Numeric (5)
,'' SZMTF2 -- Freeze Time Fence Days [Generic Edit] Numeric (5)
,'' SZMTF3 -- Message Time Fence Days [Generic Edit] Numeric (5)
,'' SZMTF4 -- MPS/MRP Time Fence 4 [Generic Edit] Numeric (5)
,'' SZMTF5 -- Shipment Leadtime Offset [Generic Edit] Numeric (5)
,'' SZEXPD -- Expedite Damper Days [Generic Edit] Numeric (5)
,'' SZDEFD -- Defer Damper Days [Generic Edit] Numeric (5)
,'' SZSFLT -- Safety Leadtime [Generic Edit] Numeric (5)
,'' SZMAKE -- Make/Buy Code [UDC (H40 MA)] Character (1)
,'' SZCOBY -- Co-Products/By-Products/Intermediate [UDC (H40 CO)] Character (1)
,'' SZLLX -- Low Level Code [Generic Edit] Numeric (3)
,'' SZCMGL -- Commitment Method [UDC (H40 CM)] Character (1)
,'' SZCOMH -- Commitment - Specific (Days) [Generic Edit] Numeric (3)
,'' SZAVRT -- Replenishment Hours - Standard [Generic Edit] Numeric (15)
,'' SZUPCN -- UPC Number [Generic Edit] String (13)
,'' SZSCC0 -- Aggregate SCC Code (PI=0) [Generic Edit] String (14)
,'' SZUMDF -- Unit of Measure - Aggregate UPC [UDC (00 UM)] String (2)
,'' SZUMS0 -- Unit of Measure - SCC(PI=0) [UDC (00 UM)] String (2)
,'' SZUMUP -- Unit of Measure - UPC [UDC (00 UM)] String (2)
,'' SZUMS1 -- Unit of Measure - SCC(PI=1) [UDC (00 UM)] String (2)
,'' SZUMS2 -- Unit of Measure - SCC(PI=2) [UDC (00 UM)] String (2)
,'' SZUMS3 -- Unit of Measure - SCC(PI=3) [UDC (00 UM)] String (2)
,'' SZUMS4 -- Unit of Measure - SCC(PI=4) [UDC (00 UM)] String (2)
,'' SZUMS5 -- Unit of Measure - SCC(PI=5) [UDC (00 UM)] String (2)
,'' SZUMS6 -- Unit of Measure - SCC(PI=6) [UDC (00 UM)] String (2)
,'' SZUMS7 -- Unit of Measure - SCC(PI=7) [UDC (00 UM)] String (2)
,'' SZUMS8 -- Unit of Measure - SCC(PI=8) [UDC (00 UM)] String (2)
,'' SZWTRQ -- Item Weight Required Y/N [Generic Edit] Character (1)
,'' SZEQTY -- Container Code [UDC (46 EQ)] String (5)
,'' SZPOC -- Issue and Receipt [UDC (43 IR)] Character (1)
,'' SZMCU -- Business Unit [Generic Edit] String (12)
,'' SZMMCU -- Branch [Generic Edit] String (12)
,'' SZVEND -- Primary / Last Supplier Number [Generic Edit] Numeric (8)
,'' SZORIG -- Country of Origin [UDC (00 CN)] String (3)
,'' SZROPI -- Reorder Point - Input [Generic Edit] Numeric (15)
,'' SZROQI -- Reorder Quantity - Input [Generic Edit] Numeric (15)
,'' SZRQMX -- Reorder Quantity - Maximum [Generic Edit] Numeric (15)
,'' SZRQMN -- Reorder Quantity - Minimum [Generic Edit] Numeric (15)
,'' SZWOMO -- Quantity - Order Multiples (SO/PO) [Generic Edit] Numeric (7)
,'' SZSERV -- Service Level [Generic Edit] Numeric (7)
,'' SZSAFE -- Safety Stock [Generic Edit] Numeric (15)
,'' SZFUF1 -- AIA Document Flag [UDC (H40 FU)] Character (1)
,'' SZTX -- Purchasing Taxable (Y/N) [UDC (H00 TV)] Character (1)
,'' SZTAX1 -- Sales Taxable (Y/N) [UDC (H00 TV)] Character (1)
,'' SZMRPD -- Item Display Code [UDC (H41 MR)] Character (1)
,'' SZMRPC -- Flag - Net Change [UDC (H41 MQ)] Character (1)
,'' SZUPC -- Units - Per Container [Generic Edit] Numeric (15)
,'' SZMERL -- Item Revision Level [Generic Edit] String (3)
,'' SZECO -- ECO Number [Generic Edit] String (12)
,'' SZECTY -- Engineering Change Reason [UDC (40 CR)] String (2)
,'' SZECOD -- Date - Engineering Change Date [Generic Edit] Date (6)
,'' SZMOVD -- Move Hours - Standard [Generic Edit] Numeric (5)
,'' SZQUED -- Queue Hours - Standard [Generic Edit] Numeric (5)
,'' SZSETL -- Setup Labor - Standard [Generic Edit] Numeric (15)
,'' SZSRNK -- Shrink Factor [Generic Edit] Numeric (15)
,'' SZSRKF -- Shrink Factor Method [UDC (H40 SR)] Character (1)
,'' SZTIMB -- Time Basis Code [UDC (30 TB)] Character (1)
,'' SZBQTY -- Units - Batch Quantity [Generic Edit] Numeric (15)
,'' SZMULT -- Quantity - Order Multiples (MRP) [Generic Edit] Numeric (15)
,'' SZLFDJ -- Date - Future Use [Generic Edit] Date (6)
,'' SZMLOT -- Mix Dates / Lots (Y/N) [Generic Edit] Character (1)
,'' SZLOCN -- Location [Generic Edit] String (20)
,'' SZLOTN -- Lot/Serial Number [Generic Edit] String (30)
,'' SZURCD -- User Reserved Code [Generic Edit] String (2)
,'' SZURDT -- User Reserved Date [Generic Edit] Date (6)
,'' SZURAT -- User Reserved Amount [Generic Edit] Numeric (15)
,'' SZURAB -- User Reserved Number [Generic Edit] Numeric (8)
,'' SZURRF -- User Reserved Reference [Generic Edit] String (15)
,'' SZTORG -- Transaction Originator [Generic Edit] String (10)
,'' SZSTAW -- Status [UDC (00 WS)] Character (1)
,'' SZEFFT -- Effective - Thru Date [Generic Edit] Date (6)
,'' SZDOC -- Document (Voucher Invoice etc.) [Generic Edit] Numeric (8)
,'' SZDCT -- Document Type [UDC (00 DT)] String (2)
,'' SZUSER -- User ID [Generic Edit] String (10)
,'' SZPID -- Program ID [Generic Edit] String (10)
,'' SZJOBN -- Work Station ID [Generic Edit] String (10)
,'' SZUPMJ -- Date - Updated [Generic Edit] Date (6)
,'' SZTDAY -- Time of Day [Generic Edit] Numeric (6)
,'' SZTMPL -- Template [Generic Edit] String (20)
,'' SZSEG1 -- Segment 1 [Generic Edit] String (10)
,'' SZSEG2 -- Segment 2 [Generic Edit] String (10)
,'' SZSEG3 -- Segment 3 [Generic Edit] String (10)
,'' SZSEG4 -- Segment 4 [Generic Edit] String (10)
,'' SZSEG5 -- Segment 5 [Generic Edit] String (10)
,'' SZSEG6 -- Segment 6 [Generic Edit] String (10)
,'' SZSEG7 -- Segment 7 [Generic Edit] String (10)
,'' SZSEG8 -- Segment 8 [Generic Edit] String (10)
,'' SZSEG9 -- Segment 9 [Generic Edit] String (10)
,'' SZSEG0 -- Segment 10 [Generic Edit] String (10)
,'' SZAING -- Active Ingredient Flag [Generic Edit] Character (1)
,'' SZCMDM -- Commitment Date Method [UDC (H40 CD)] Character (1)
,'' SZDPPO -- Dual Picking Process Option [Generic Edit] Character (1)
,'' SZDUAL -- Dual Unit Of Measure Item [Generic Edit] Character (1)
,'' SZLECM -- Lot Expiraton Date Calculation Method [UDC (H41 EC)] Character (1)
,'' SZMIC -- Matrix Controlled [UDC (41 MA)] Character (1)
,'' SZXDCK -- Cross-Docking Flag [Generic Edit] Character (1)
,'' SZDLTL -- Dual Tolerance [Generic Edit] Numeric (7)
,'' SZLEDD -- Lot Effective Default Days [Generic Edit] Numeric (6)
,'' SZPEFD -- Purchasing Effective Days [Generic Edit] Numeric (6)
,'' SZSBDD -- Sell By Default Days [Generic Edit] Numeric (6)
,'' SZU1DD -- User Lot Date 1 Default Days [Generic Edit] Numeric (6)
,'' SZU2DD -- User Lot Date 2 Default Days [Generic Edit] Numeric (6)
,'' SZU3DD -- User Lot Date 3 Default Days [Generic Edit] Numeric (6)
,'' SZU4DD -- User Lot Date 4 Default Days [Generic Edit] Numeric (6)
,'' SZU5DD -- User Lot Date 5 Default Days [Generic Edit] Numeric (6)
,'' SZBBDD -- Best Before Default Days [Generic Edit] Numeric (6)
,'' SZLOTC -- Lot Status Code Expanded [Generic Edit] String (3)
,'' SZEXPI -- Explode Item (1/0) [Generic Edit] Character (1)
,'' SZCONB -- Consumable [Generic Edit] Character (1)
,'' SZPRI1 -- Priority One Alert Level [Generic Edit] Numeric (15)
,'' SZPRI2 -- Priority Two Alert Level [Generic Edit] Numeric (15)
,'' SZGCMP -- Composition [Generic Edit] Character (1)
,'' SZAPSC -- Constraints Flag [UDC (42 AC)] Character (1)
,'' SZCMETH -- Method - Configurator Costing [UDC (41 CM)] Character (1)
,'' SZLAF -- Lot Audit Flag [Generic Edit] Character (1)
,'' SZLTFM -- Special Lot Format [Generic Edit] Character (1)
,'' SZRWLA -- Restrict Work Order Lot Assignment [Generic Edit] Character (1)
,'' SZLNPA -- Lot Number Pre-Assignment [Generic Edit] Character (1)
,'' SZASHL -- Allow Shipping of Held Lots [Generic Edit] Character (1)
,'' SZVMINV -- Vendor Managed Inventory [Generic Edit] Character (1)
,'' SZLTCV -- Leadtime Conversion Factor [Generic Edit] Numeric (15)
,'' SZOPTH -- Minimum Operational Threshold [Generic Edit] Numeric (15)
,'' SZCUTH -- Minimum Cumulative Threshold [Generic Edit] Numeric (15)
,'' SZUMTH -- Operational Threshold Unit of Measure [UDC (31B UM)] String (3)
,'' SZLMFG -- Lean Manufacturing Flag [Generic Edit] Character (1)
,'' SZLINE -- Line/Cell Identifier [Generic Edit] String (12)
,'' SZDFTPCT -- Total Product Cycle Time [Generic Edit] Numeric (20)
,'' SZKBIT -- Kanban Item [Generic Edit] Character (1)
,'' SZDFENDITM -- Demand Flow End Item Flag [Generic Edit] Character (1)
,'' SZKANEXLL -- Kanban Explode to Lower Level [Generic Edit] Character (1)
,'' SZSCPSELL -- Sellable Item [UDC (34A SA)] Character (1)
,'' SZMOPTH -- Maximum Operational Threshold [Generic Edit] Numeric (15)
,'' SZMCUTH -- Maximum Cumulative Threshold [Generic Edit] Numeric (15)
,'' SZCUMTH -- Cumulative Threshold Unit of Measure [UDC (31B UM)] String (3)
,'' SZATPRN -- ATP Rule Name [Generic Edit] String (80)
,'' SZATPCA -- Check ATP [UDC (34A CA)] Character (1)
,'' SZATPAC -- ATP Components [UDC (34A AP)] String (5)
,'' SZCOORE -- Country of Origin Required Flag [Generic Edit] Character (1)
,'' SZVCPFC -- ATO Forecast Control [UDC (34A CF)] String (20)
,'' SZPNYN -- Production Number Controlled [Generic Edit] Character (1)

FROM

TBD