/*
    F41021Z1 - Item Location and Balances
    VER0001 -  Tom Sampson
*/

SELECT

 '' SZEDUS -- EDI - User ID [Generic Edit] String (10)
,'' SZEDBT -- EDI - Batch Number [Generic Edit] String (15)
,'' SZEDTN -- EDI - Transaction Number [Generic Edit] String (22)
,'' SZEDLN -- EDI - Line Number [Generic Edit] Numeric (7)
,'' SZEDCT -- EDI - Document Type [Generic Edit] String (2)
,'' SZTYTN -- Type - Transaction [UDC (00 TT)] String (8)
,'' SZEDFT -- EDI - Translation Format [Generic Edit] String (10)
,'' SZEDDT -- EDI - Transmission Date [Generic Edit] Date (6)
,'' SZDRIN -- Direction Indicator [UDC (00 DN)] Character (1)
,'' SZEDDL -- EDI - Detail Lines Processed [Generic Edit] Numeric (5)
,'' SZEDSP -- EDI - Successfully Processed [Generic Edit] Character (1)
,'' SZPNID -- Trading Partner ID [Generic Edit] String (15)
,'' SZTNAC -- Transaction Action [UDC (00 TA)] String (2)
,'' SZITM -- Item Number - Short [Generic Edit] Numeric (8)
,'' SZMCU -- Business Unit [Generic Edit] String (12)
,'' SZLOCN -- Location [Generic Edit] String (20)
,'' SZLOTN -- Lot/Serial Number [Generic Edit] String (30)
,'' SZPBIN -- Primary Location (P/S) [Generic Edit] Character (1)
,'' SZGLPT -- Category - G/L [UDC (41 9)] String (4)
,'' SZLOTS -- Lot Status Code [UDC (41 L)] Character (1)
,'' SZLRCJ -- Date - Last Receipt (Julian) [Generic Edit] Date (6)
,'' SZPQOH -- Quantity on Hand - Primary units [Generic Edit] Numeric (15)
,'' SZPBCK -- Quantity on Backorder [Generic Edit] Numeric (15)
,'' SZPREQ -- Quantity on Purchase Order-primary units [Generic Edit] Numeric (15)
,'' SZQWBO -- Quantity on Work Order Receipt [Generic Edit] Numeric (15)
,'' SZOT1P -- Quantity 1 - Other primary units [Generic Edit] Numeric (15)
,'' SZOT2P -- Quantity 2 - Other primary units [Generic Edit] Numeric (15)
,'' SZOT1A -- Quantity - Other Purchasing 1 [Generic Edit] Numeric (15)
,'' SZHCOM -- Quantity - Hard Committed [Generic Edit] Numeric (15)
,'' SZPCOM -- Quantity Soft Committed [Generic Edit] Numeric (15)
,'' SZFCOM -- Quantity on Future Commit [Generic Edit] Numeric (15)
,'' SZFUN1 -- Quantity - Work Order Soft Commit [Generic Edit] Numeric (15)
,'' SZQOWO -- Quantity - Work Order Hard Commit [Generic Edit] Numeric (15)
,'' SZQTTR -- Units - In Transit - Primary units [Generic Edit] Numeric (15)
,'' SZQTIN -- Units - In Inspection - Primary units [Generic Edit] Numeric (15)
,'' SZQONL -- Quantity - On Loan to Manufacturing [Generic Edit] Numeric (15)
,'' SZQTRI -- Quantity Inbound - Warehouse [Generic Edit] Numeric (15)
,'' SZQTRO -- Quantity Outbound - Warehouse [Generic Edit] Numeric (15)
,'' SZNCDJ -- Date - Next Count (Julian) [Generic Edit] Date (6)
,'' SZQTY1 -- Future Use Quantity [Generic Edit] Numeric (15)
,'' SZQTY2 -- Future Use Quantity 2 [Generic Edit] Numeric (15)
,'' SZQTO1 -- Units - In Operation 1 - Primary units [Generic Edit] Numeric (15)
,'' SZQTO2 -- Units - In Operation 2 - Primary units [Generic Edit] Numeric (15)
,'' SZLITM -- 2nd Item Number [Generic Edit] String (25)
,'' SZAITM -- 3rd Item Number [Generic Edit] String (25)
,'' SZTRQT -- Quantity Available [Generic Edit] Numeric (15)
,'' SZILOD -- Item Level Of Detail [Generic Edit] Character (1)
,'' SZURCD -- User Reserved Code [Generic Edit] String (2)
,'' SZURDT -- User Reserved Date [Generic Edit] Date (6)
,'' SZURAT -- User Reserved Amount [Generic Edit] Numeric (15)
,'' SZURAB -- User Reserved Number [Generic Edit] Numeric (8)
,'' SZURRF -- User Reserved Reference [Generic Edit] String (15)
,'' SZTORG -- Transaction Originator [Generic Edit] String (10)
,'' SZUSER -- User ID [Generic Edit] String (10)
,'' SZPID -- Program ID [Generic Edit] String (10)
,'' SZJOBN -- Work Station ID [Generic Edit] String (10)
,'' SZUPMJ -- Date - Updated [Generic Edit] Date (6)
,'' SZTDAY -- Time of Day [Generic Edit] Numeric (6)
,'' SZHCMS -- Secondary Quantity Hard Committed [Generic Edit] Numeric (15)
,'' SZPJCM -- Project Hard Committed Quantity in Prima [Generic Edit] Numeric (15)
,'' SZPJDM -- Project Hard Committed Quantity in Secon [Generic Edit] Numeric (15)
,'' SZSCMS -- Secondary Quantity Soft Committed [Generic Edit] Numeric (15)
,'' SZSIBW -- Secondary Quantity Inbound - Warehouse [Generic Edit] Numeric (15)
,'' SZSOBW -- Secondary Quantity Outbound - Warehouse [Generic Edit] Numeric (15)
,'' SZSQOH -- Quantity on Hand - in Secondary units [Generic Edit] Numeric (15)
,'' SZSQWO -- Secondary Quantity on Work Order Receipt [Generic Edit] Numeric (15)
,'' SZSREQ -- Quantity on Purchase Order - Secondary [Generic Edit] Numeric (15)
,'' SZSWHC -- Secondary Quantity WO Hard Commit [Generic Edit] Numeric (15)
,'' SZSWSC -- SecondaryQuantity W.O. Soft Commit [Generic Edit] Numeric (15)
,'' SZCFGSID -- Unique Configuration ID [Generic Edit] String (32)
,'' SZLOTC -- Lot Status Code Expanded [Generic Edit] String (3)

FROM

TBD