/*
    F03012Z1 - Customer Master
    VER0001 -  Tom Sampson
*/

SELECT

 '' VOEDUS -- EDI - User ID [Generic Edit] String (10)
,'' VOEDBT -- EDI - Batch Number [Generic Edit] String (15)
,'' VOEDTN -- EDI - Transaction Number [Generic Edit] String (22)
,'' VOEDLN -- EDI - Line Number [Generic Edit] Numeric (7)
,'' VOEDCT -- EDI - Document Type [Generic Edit] String (2)
,'' VOTYTN -- Type - Transaction [UDC (00 TT)] String (8)
,'' VOEDFT -- EDI - Translation Format [Generic Edit] String (10)
,'' VOEDDT -- EDI - Transmission Date [Generic Edit] Date (6)
,'' VODRIN -- Direction Indicator [UDC (00 DN)] Character (1)
,'' VOEDDL -- EDI - Detail Lines Processed [Generic Edit] Numeric (5)
,'' VOEDSP -- EDI - Successfully Processed [Generic Edit] Character (1)
,'' VOPNID -- Trading Partner ID [Generic Edit] String (15)
,'' VOTNAC -- Transaction Action [UDC (00 TA)] String (2)
,'' VOAN8 -- Address Number [Generic Edit] Numeric (8)
,'' VOCO -- Company [Generic Edit] String (5)
,'' VOARC -- G/L Offset [Generic Edit] String (4)
,'' VOMCUR -- Business Unit - A/R Default [Generic Edit] String (12)
,'' VOOBAR -- Object - Accounts Receivable Default [Generic Edit] String (6)
,'' VOAIDR -- Subsidiary - Accounts Receivable Default [Generic Edit] String (8)
,'' VOKCOR -- Document Company (A/R Model Document) [Generic Edit] String (5)
,'' VODCAR -- Document - A/R Default for Model JE [Generic Edit] Numeric (8)
,'' VODTAR -- Document Type - A/R Default for Model JE [UDC (00 DT)] String (2)
,'' VOCRCD -- Currency Code - From [Generic Edit] String (3)
,'' VOTXA1 -- Tax Rate/Area [Generic Edit] String (10)
,'' VOEXR1 -- Tax Expl Code 1 [UDC (00 EX)] String (2)
,'' VOACL -- Amount - Credit Limit [Generic Edit] Numeric (15)
,'' VOHDAR -- Hold Invoices [UDC (H01 HC)] Character (1)
,'' VOTRAR -- Payment Terms - A/R [Generic Edit] String (3)
,'' VOSTTO -- Send Statement to C/P [UDC (H00 SV)] Character (1)
,'' VORYIN -- Payment Instrument [UDC (00 PY)] Character (1)
,'' VOSTMT -- Print Statement Y/N [UDC (H03 ST)] Character (1)
,'' VOARPY -- Alternate Payor [Generic Edit] Numeric (8)
,'' VOATCS -- Auto Receipt (Y/N) [Generic Edit] Character (1)
,'' VOSITO -- Send Invoice to C/P [UDC (H00 SI)] Character (1)
,'' VOSQNL -- Ledger Inquiry Sequence [UDC (H01 SQ)] Character (1)
,'' VOALGM -- Auto Receipt Algorithm Method [UDC (01 AA)] String (2)
,'' VOCYCN -- Statement Cycle [Generic Edit] String (2)
,'' VOBO -- Balance Forward-Open Item [UDC (H03 BO)] Character (1)
,'' VOTSTA -- Temporary Credit Message [UDC (00 CM)] String (2)
,'' VOCKHC -- Credit Check Handling Code [Generic Edit] Character (1)
,'' VODLC -- Date - Last Credit Review [Generic Edit] Date (6)
,'' VODNLT -- Delinquency Notice (Y/N) [Generic Edit] Character (1)
,'' VOPLCR -- Person Completing Last Credit Limit Rev [Generic Edit] String (10)
,'' VORVDJ -- Date - Recall for Review [Generic Edit] Date (6)
,'' VODSO -- Days Sales Outstanding [Generic Edit] Numeric (5)
,'' VOCMGR -- Credit Manager [UDC (01 CR)] String (10)
,'' VOCLMG -- Collection Manager [UDC (01 CM)] String (10)
,'' VODLQT -- Dunning Letters - Number Sent [Generic Edit] Numeric (3)
,'' VODLQJ -- Date - Last Dunning Letter [Generic Edit] Date (6)
,'' VONBRR -- Reminders - Number of Reminders to Send [UDC (H00 NB)] Character (1)
,'' VOCOLL -- Collection Report (Y/N) [UDC (H00 CO)] Character (1)
,'' VONBR1 -- Number of Sent Reminders - 1 [Generic Edit] Numeric (3)
,'' VONBR2 -- Number of Sent Reminders - 2 [Generic Edit] Numeric (3)
,'' VONBR3 -- Number of Sent Reminders - 3 [Generic Edit] Numeric (3)
,'' VONBCL -- Number of Invoices to Collection Report [Generic Edit] Numeric (3)
,'' VOAFC -- Apply Finance Charges - Y/N [UDC (H00 AF)] Character (1)
,'' VOFD -- Finance Charge Days [Generic Edit] Numeric (3)
,'' VOFP -- Percentage Factor [Generic Edit] Numeric (9)
,'' VOCFCE -- Finance Charge - Create Entries Y/N [Generic Edit] Character (1)
,'' VOAB2 -- Address Book - Pending Cash Receipts [Generic Edit] Character (1)
,'' VODT1J -- Date - Last Statement Date [Generic Edit] Date (6)
,'' VODFIJ -- Date - First Invoice [Generic Edit] Date (6)
,'' VODLIJ -- Date - Last Invoice (Julian) [Generic Edit] Date (6)
,'' VOABC1 -- ABC Code Sales [UDC (H01 A1)] Character (1)
,'' VOABC2 -- ABC Code 2 - Investment - Inventory [UDC (H01 A2)] Character (1)
,'' VOABC3 -- ABC Code Average Days [UDC (H01 A3)] Character (1)
,'' VOFNDJ -- Date - Financial Stmts on Hand [Generic Edit] Date (6)
,'' VODLP -- Date - Last Paid [Generic Edit] Date (6)
,'' VODB -- Dun & Bradstreet Rating [UDC (01 DB)] String (3)
,'' VODNBJ -- Date - Dun & Bradstreet [Generic Edit] Date (6)
,'' VOTRW -- TRW Rating [UDC (01 TR)] String (3)
,'' VOTWDJ -- TRW Date [Generic Edit] Date (6)
,'' VOAVD -- Average Days Late [Generic Edit] Numeric (3)
,'' VOCRCA -- Currency Code - A/B Amounts [Generic Edit] String (3)
,'' VOAD -- Amount - Due [Generic Edit] Numeric (15)
,'' VOAFCP -- Amount - Prior Year Finance Charges [Generic Edit] Numeric (15)
,'' VOAFCY -- Amount - YTD Finance Charges [Generic Edit] Numeric (15)
,'' VOASTY -- Amount - Invoiced This Year [Generic Edit] Numeric (15)
,'' VOSPYE -- Amount - Invoiced Prior Year [Generic Edit] Numeric (15)
,'' VOAHB -- Amount - High Balance [Generic Edit] Numeric (15)
,'' VOALP -- Amount - Last Applied [Generic Edit] Numeric (15)
,'' VOABAM -- Amount - Address Book [Generic Edit] Numeric (15)
,'' VOABA1 -- Amount - Address Book [Generic Edit] Numeric (15)
,'' VOAPRC -- Amount - Open Order [Generic Edit] Numeric (15)
,'' VOMAXO -- Maximum Order Value [Generic Edit] Numeric (15)
,'' VOMINO -- Minimum Order Value [Generic Edit] Numeric (15)
,'' VOOYTD -- Orders - Year-to-Date [Generic Edit] Numeric (3)
,'' VOOPY -- Orders - Prior Year [Generic Edit] Numeric (3)
,'' VOPOPN -- Person Opening Account [Generic Edit] String (10)
,'' VODAOJ -- Date - Account Opened [Generic Edit] Date (6)
,'' VOAN8R -- Related - Address Number [Generic Edit] Numeric (8)
,'' VOBADT -- Billing Address Type [UDC (H42 BA)] Character (1)
,'' VOCPGP -- Customer Price Group [UDC (40 PC)] String (8)
,'' VOORTP -- Order Template [UDC (40 OT)] String (8)
,'' VOTRDC -- Discount - Trade [Generic Edit] Numeric (7)
,'' VOINMG -- Print Message [UDC (40 PM)] String (10)
,'' VOEXHD -- Credit Hold Exempt [Generic Edit] Character (1)
,'' VOHOLD -- Hold Orders Code [UDC (42 HC)] String (2)
,'' VOROUT -- Route Code [UDC (42 RT)] String (3)
,'' VOSTOP -- Stop Code [UDC (42 SP)] String (3)
,'' VOZON -- Zone Number [UDC (40 ZN)] String (3)
,'' VOCARS -- Carrier Number [Generic Edit] Numeric (8)
,'' VODEL1 -- Delivery Instructions Line 1 [Generic Edit] String (30)
,'' VODEL2 -- Delivery Instructions Line 2 [Generic Edit] String (30)
,'' VOLTDT -- Transit Days [Generic Edit] Numeric (5)
,'' VOFRTH -- Freight Handling Code [UDC (42 FR)] String (3)
,'' VOAFT -- Apply Freight - Y/N [Generic Edit] Character (1)
,'' VOAPTS -- Partial Line Shipments Allowed (Y/N) [Generic Edit] Character (1)
,'' VOSBAL -- Substitutes Allowed (Y/N) [Generic Edit] Character (1)
,'' VOBACK -- Backorders Allowed (Y/N) [Generic Edit] Character (1)
,'' VOPORQ -- Customer PO Required (Y/N) [Generic Edit] Character (1)
,'' VOPRIO -- Priority - Processing [UDC (H40 PR)] Character (1)
,'' VOARTO -- Credit Check Level [UDC (H42 AR)] Character (1)
,'' VOINVC -- Invoice Copies [Generic Edit] Numeric (2)
,'' VOICON -- Invoice Consolidation [Generic Edit] Character (1)
,'' VOBLFR -- Billing Frequency [UDC (H42 BL)] Character (1)
,'' VONIVD -- Next Invoice Date [Generic Edit] Date (6)
,'' VOLEDJ -- Date - License Expiration [Generic Edit] Date (6)
,'' VOPLST -- Price Pick List (Y/N) [Generic Edit] Character (1)
,'' VOMORD -- Merge Orders (Y/N) [Generic Edit] Character (1)
,'' VOCMC1 -- Commission Code 1 [Generic Edit] Numeric (8)
,'' VOCMR1 -- Rate - Commission 1 [Generic Edit] Numeric (7)
,'' VOCMC2 -- Commission Code 2 [Generic Edit] Numeric (8)
,'' VOCMR2 -- Rate - Commission 2 [Generic Edit] Numeric (7)
,'' VOPALC -- Pallet Control [Generic Edit] Character (1)
,'' VOVUMD -- Unit of Measure - Volume Display [UDC (00 UM)] String (2)
,'' VOWUMD -- Unit of Measure - Weight Display [UDC (00 UM)] String (2)
,'' VOEDPM -- Batch Processing Mode [UDC (H40 EE)] Character (1)
,'' VOEDII -- Item Type Identifier [UDC (40 II)] Character (1)
,'' VOEDCI -- Customer Type Identifier [UDC (40 CI)] Character (1)
,'' VOEDQD -- Quantity Decimals [Generic Edit] Numeric (1)
,'' VOEDAD -- Amount Decimals [Generic Edit] Numeric (1)
,'' VOEDF1 -- Delivery Note [Generic Edit] Character (1)
,'' VOEDF2 -- Item Restrictions [UDC (H40 ED)] Character (1)
,'' VOSI01 -- Partial Order Shipments Allowed (Y/N) [Generic Edit] Character (1)
,'' VOSI02 -- COA Print (Y/N) [Generic Edit] Character (1)
,'' VOSI03 -- Override Territory Id Assignment [Generic Edit] Character (1)
,'' VOSI04 -- Special Instruction 04 [Generic Edit] Character (1)
,'' VOSI05 -- Special Instruction 05 [Generic Edit] Character (1)
,'' VOCP01 -- Sales Price Based On Date [UDC (40 DB)] Character (1)
,'' VOASN -- Price and Adjustment Schedule [UDC (40 AS)] String (8)
,'' VODSPA -- Print Adjustments on Invoice (Y/N) [Generic Edit] Character (1)
,'' VOCRMD -- Send Method [UDC (00 SM)] Character (1)
,'' VOPLY -- Policy Number (Internal) [Generic Edit] Numeric (5)
,'' VOMAN8 -- Deduction Manager [Generic Edit] Numeric (8)
,'' VOARL -- Auto Receipts Execution List [Generic Edit] String (10)
,'' VOAMCR -- Administration Credit Limit [Generic Edit] Numeric (15)
,'' VOAC01 -- Category Code - Address Book 01 [UDC (01 01)] String (3)
,'' VOAC02 -- Category Code - Address Book 02 [UDC (01 02)] String (3)
,'' VOAC03 -- Category Code - Address Book 03 [UDC (01 03)] String (3)
,'' VOAC04 -- Category Code - Address Book 04 [UDC (01 04)] String (3)
,'' VOAC05 -- Category Code - Address Book 05 [UDC (01 05)] String (3)
,'' VOAC06 -- Category Code - Address Book 06 [UDC (01 06)] String (3)
,'' VOAC07 -- Category Code - Address Book 07 [UDC (01 07)] String (3)
,'' VOAC08 -- Category Code - Address Book 08 [UDC (01 08)] String (3)
,'' VOAC09 -- Category Code - Address Book 09 [UDC (01 09)] String (3)
,'' VOAC10 -- Category Code - Address Book 10 [UDC (01 10)] String (3)
,'' VOAC11 -- Sales Region [UDC (01 11)] String (3)
,'' VOAC12 -- Category Code - Address Book 12 [UDC (01 12)] String (3)
,'' VOAC13 -- Category Code - Address Book 13 [UDC (01 13)] String (3)
,'' VOAC14 -- Category Code - Address Book 14 [UDC (01 14)] String (3)
,'' VOAC15 -- Category Code - Address Book 15 [UDC (01 15)] String (3)
,'' VOAC16 -- Category Code - Address Book 16 [UDC (01 16)] String (3)
,'' VOAC17 -- Category Code - Address Book 17 [UDC (01 17)] String (3)
,'' VOAC18 -- Category Code - Address Book 18 [UDC (01 18)] String (3)
,'' VOAC19 -- Category Code - Address Book 19 [UDC (01 19)] String (3)
,'' VOAC20 -- Category Code - Address Book 20 [UDC (01 20)] String (3)
,'' VOAC21 -- Category Code - Address Book 21 [UDC (01 21)] String (3)
,'' VOAC22 -- Category Code - Address Book 22 [UDC (01 22)] String (3)
,'' VOAC23 -- Category Code - Address Book 23 [UDC (01 23)] String (3)
,'' VOAC24 -- Category Code - Address Book 24 [UDC (01 24)] String (3)
,'' VOAC25 -- Category Code - Address Book 25 [UDC (01 25)] String (3)
,'' VOAC26 -- Category Code - Address Book 26 [UDC (01 26)] String (3)
,'' VOAC27 -- Category Code - Address Book 27 [UDC (01 27)] String (3)
,'' VOAC28 -- Category Code - Address Book 28 [UDC (01 28)] String (3)
,'' VOAC29 -- Category Code - Address Book 29 [UDC (01 29)] String (3)
,'' VOAC30 -- Category Code - Address Book 30 [UDC (01 30)] String (3)
,'' VOSLPG -- Program Name - Shipping Labels [Generic Edit] String (10)
,'' VOSLDW -- Version Name - Shipping Label Program [Generic Edit] String (10)
,'' VOCFPP -- Configuration Pick and Pack [Generic Edit] String (18)
,'' VOCFSP -- Configuration Standard Carton Pack [Generic Edit] String (18)
,'' VOCFDF -- Default Configuration [Generic Edit] Character (1)
,'' VORQ01 -- Requires Packaging Code [Generic Edit] Character (1)
,'' VORQ02 -- Requires Weight Code [Generic Edit] Character (1)
,'' VORQ03 -- Requires Identification - Code 1 [Generic Edit] Character (1)
,'' VORQ04 -- Requires Identification - Code 2 [Generic Edit] Character (1)
,'' VORQ05 -- Requires Transportation Method [Generic Edit] Character (1)
,'' VORQ06 -- Requires Routing [Generic Edit] Character (1)
,'' VORQ07 -- Requires Equipment [Generic Edit] Character (1)
,'' VORQ08 -- Requires Reference Number 1 [Generic Edit] Character (1)
,'' VORQ09 -- Requires Reference Number 2 [Generic Edit] Character (1)
,'' VODR03 -- Default Identification Code Qualifier 1 [UDC (41 X3)] String (2)
,'' VODR04 -- Default Identification Code Qualifier 2 [UDC (41 X3)] String (2)
,'' VODR08 -- Default Reference Number Qualifier 1 [UDC (41 X6)] String (2)
,'' VODR09 -- Default Identification Code Qualifier [UDC (41 X6)] String (2)
,'' VOURDT -- User Reserved Date [Generic Edit] Date (6)
,'' VOURCD -- User Reserved Code [Generic Edit] String (2)
,'' VOURAT -- User Reserved Amount [Generic Edit] Numeric (15)
,'' VOURAB -- User Reserved Number [Generic Edit] Numeric (8)
,'' VOURRF -- User Reserved Reference [Generic Edit] String (15)
,'' VOTORG -- Transaction Originator [Generic Edit] String (10)
,'' VOUSER -- User ID [Generic Edit] String (10)
,'' VOPID -- Program ID [Generic Edit] String (10)
,'' VOJOBN -- Work Station ID [Generic Edit] String (10)
,'' VOUPMT -- Time - Last Updated [Generic Edit] Numeric (6)
,'' VOUPMJ -- Date - Updated [Generic Edit] Date (6)
,'' VOTDAY -- Time of Day [Generic Edit] Numeric (6)
,'' VOPRGF -- Purge Flag [Generic Edit] Character (1)
,'' VOBYAL -- Bypass Audit Logging [Generic Edit] Character (1)
,'' VOBSC -- Buying Segment Code [UDC (42B BS)] String (10)
,'' VOASHL -- Allow Shipping of Held Lots [Generic Edit] Character (1)
,'' VOPRSN -- Preference Schedule [Generic Edit] String (8)
,'' VOOPBO -- OP Business Objective [UDC (34A BO)] String (30)
,'' VOAPSB -- APS Business Unit [Generic Edit] Character (1)
,'' VOTIER1 -- Tier [UDC (01 TI)] String (5)
,'' VOPWPCP -- Pay When Paid Cash Receipt Threshold [Generic Edit] Numeric (5)
,'' VOCUSTS -- Customer Status [UDC (01 TY)] Character (1)
,'' VOSTOF -- Override Sales Team Assignment [Generic Edit] Character (1)
,'' VOTERRID -- Territory Id [Generic Edit] Numeric (15)
,'' VOCIG -- Industry Group [Generic Edit] Numeric (15)
,'' VODTEE -- Date - Entered [Generic Edit] JDE UTime (11)
,'' VOGOPASF -- GOP Arrival or Ship Flag [UDC (34A AS)] Character (1)

FROM

TBD